### ISSUE TITLE
FunctionTransformer should support all 1-parameter Numpy universal functions (ufuncs)

### ISSUE THREAD

**Issue by keithgw** [jpmml/sklearn2pmml#11]
Trying to get `FunctionTransformer` to work with `sklearn2pmml`, and am getting the following error:

```
Aug 18, 2016 3:49:50 PM org.jpmml.sklearn.Main run
INFO: Parsing DataFrameMapper PKL..
Aug 18, 2016 3:49:50 PM org.jpmml.sklearn.Main run
INFO: Parsed DataFrameMapper PKL in 36 ms.
Aug 18, 2016 3:49:50 PM org.jpmml.sklearn.Main run
INFO: Converting DataFrameMapper..
Aug 18, 2016 3:49:50 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert DataFrameMapper
java.lang.IllegalArgumentException: The function object (Java class net.razorvine.pickle.objects.ClassDictConstructor) is not a Numpy universal function
	at sklearn.preprocessing.FunctionTransformer.encodeFeatures(FunctionTransformer.java:54)
	at sklearn_pandas.DataFrameMapper.encodeFeatures(DataFrameMapper.java:70)
	at org.jpmml.sklearn.Main.run(Main.java:146)
	at org.jpmml.sklearn.Main.main(Main.java:107)
Caused by: java.lang.ClassCastException: net.razorvine.pickle.objects.ClassDictConstructor cannot be cast to numpy.core.UFunc
	at sklearn.preprocessing.FunctionTransformer.encodeFeatures(FunctionTransformer.java:52)
	... 3 more

Exception in thread "main" java.lang.IllegalArgumentException: The function object (Java class net.razorvine.pickle.objects.ClassDictConstructor) is not a Numpy universal function
	at sklearn.preprocessing.FunctionTransformer.encodeFeatures(FunctionTransformer.java:54)
	at sklearn_pandas.DataFrameMapper.encodeFeatures(DataFrameMapper.java:70)
	at org.jpmml.sklearn.Main.run(Main.java:146)
	at org.jpmml.sklearn.Main.main(Main.java:107)
Caused by: java.lang.ClassCastException: net.razorvine.pickle.objects.ClassDictConstructor cannot be cast to numpy.core.UFunc
	at sklearn.preprocessing.FunctionTransformer.encodeFeatures(FunctionTransformer.java:52)
	... 3 more
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-213-25218f72d00f>", line 2, in <module>
    sklearn2pmml(iris_classifier, iris_mapper, "LogisticRegressionIris.pmml", with_repr = True)
  File "/Users/kwilliams/Library/Python/2.7/lib/python/site-packages/sklearn2pmml/__init__.py", line 65, in sklearn2pmml
    subprocess.check_call(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
```

As an example, I tried to apply a simple numpy universal function to the Iris data:

```
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA

from sklearn2pmml.decoration import ContinuousDomain

import pandas
import sklearn_pandas
import numpy as np

iris = load_iris()

iris_df = pandas.concat((pandas.DataFrame(iris.data[:, :], columns = ["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"]), pandas.DataFrame(iris.target, columns = ["Species"])), axis = 1)

#
# Modified from Iris Example
#
from sklearn.preprocessing import FunctionTransformer

def squarex(ary):
    return np.square(ary)

iris_mapper = sklearn_pandas.DataFrameMapper([
    (["Sepal.Length", "Sepal.Width", "Petal.Length"], [ContinuousDomain(), PCA(n_components = 2)]),
    (["Petal.Width"], [ContinuousDomain(), FunctionTransformer(squarex)]),
    ("Species", None)
])

iris = iris_mapper.fit_transform(iris_df)

#
# Step 2: training a logistic regression model
#

from sklearn.linear_model import LogisticRegressionCV

iris_X = iris[:, 0:3]
iris_y = iris[:, 3]

iris_classifier = LogisticRegressionCV()
iris_classifier.fit(iris_X, iris_y)

#
# Step 3: conversion to PMML
#

from sklearn2pmml import sklearn2pmml

sklearn2pmml(iris_classifier, iris_mapper, "LogisticRegressionIris.pmml", with_repr = True)
```

**Comment by vruusmann** [comment]
The list of supported ufuncs is rather limited at the moment:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn/preprocessing/FunctionTransformer.java#L88

In principle, it should be possible extend the list of supported ufuncs to all 1-parameter ones: http://docs.scipy.org/doc/numpy/reference/ufuncs.html

Your code example is intriguing, because you are using a local function `squarex` with the `FunctionTransformer` transformation. I was assuming that this is not possible with sklearn2pmml package, because local functions shouldn't be pickleable!? Anyway, your exception proves me wrong.

You should be able to overcome this exception, if you used `numpy.square` directly: `FunctionTransformer(numpy.square)`. However, I need to teach sklearn2pmml about this ufunc first. It will probably happen sometimes next week, as I'm currently busy upgrading all the JPMML stack to newly released PMML schema version 4.3.
