### ISSUE TITLE
Support for using an estimator as a transformer

### ISSUE THREAD

**Issue by vruusmann** [jpmml/sklearn2pmml#118]
As demonstrated in this SO question: https://stackoverflow.com/questions/53496683/customer-transformer-converting-to-pmml-by-sklearn2pmml-plugin-in-java-side

```Python
class ModelTransformer(TransformerMixin):

  def __init__(self, model):
    self.model = model

  def fit(self, X, y = None):
    self.model.fit(X = X, y = y)
    return self

  def transform(self, X):
    return self.model.predict(X)
```

**Comment by hujiayu** [comment]
Dear vruusmann, 

I found DataFrameMapper can choose feature column .  I use lr for 5 columns separately. Then , feature union 5 results of lr and fit to gdbt. So we need a customer ModelTransformer. Below is my pmml pipeline. Thanks For help !!!

    class ModelTransformer(TransformerMixin):

    def __init__(self, model):
        self.model = model

    def fit(self, *args, **kwargs):
        self.model.fit(*args, **kwargs)
        return self

    def transform(self, X, **transform_params):
        return pd.DataFrame(self.model.predict(X))

    pmml_pipeline = PMMLPipeline([
      ('features', FeatureUnion([
          ('goods_name_feat',PMMLPipeline([
              ('mapper', DataFrameMapper([('goods_name_split_text',  CountVectorizer(ngram_range=(1, 2), tokenizer=Splitter())),])),
            ('sp', SelectorProxy(SelectPercentile(chi2, percentile=25))),
            ('lr', ModelTransformer(LogisticRegression()))
        ])),
        ('goods_desc_feat', PMMLPipeline([
            ('mapper', DataFrameMapper([('goods_desc_split_text',  CountVectorizer(ngram_range=(1, 2), tokenizer=Splitter())),])),
            ('sp', SelectorProxy(SelectPercentile(chi2, percentile=25))),
            ('lr', ModelTransformer(LogisticRegression()))
        ])),
        ('hd_text_feat', PMMLPipeline([
            ('mapper', DataFrameMapper([('hd_text_split_text',  CountVectorizer(ngram_range=(1, 2), tokenizer=Splitter())),])),
            ('sp', SelectorProxy(SelectPercentile(chi2, percentile=25))),
            ('lr', ModelTransformer(LogisticRegression()))
        ])),
        ('main_text_feat', PMMLPipeline([
            ('mapper', DataFrameMapper([('main_text_split_text',  CountVectorizer(ngram_range=(1, 2), tokenizer=Splitter())),])),
            ('sp', SelectorProxy(SelectPercentile(chi2, percentile=25))),
            ('lr', ModelTransformer(LogisticRegression()))
        ])),
        ('sku_all_info_feat', PMMLPipeline([
            ('mapper', DataFrameMapper([('sku_all_info_split_text',  CountVectorizer(ngram_range=(1, 2), tokenizer=Splitter())),])),
            ('sp', SelectorProxy(SelectPercentile(chi2, percentile=25))),
            ('lr', ModelTransformer(LogisticRegression()))
        ])),
    ])),
    ('gbdt', GradientBoostingClassifier())
])

**Comment by hujiayu** [comment]
Dear vruusmann,

I used tpot StackingEstimator, I can consturct the pipeline , but I still have another problem when I try to convert pipeline to pmml by using `sklearn2pmml(pmml_pipeline, "testStaging.pmml", with_repr = True)` would you plz. help on it. Maybe I have wrong usage.

My exception:
```
java.lang.ClassCastException: org.jpmml.converter.ContinuousFeature cannot be cast to tpot.builtins.ContinuousOutputFeature
	at tpot.builtins.CategoricalOutputFeature.toContinuousFeature(CategoricalOutputFeature.java:71)
	at tpot.builtins.CategoricalOutputFeature.toContinuousFeature(CategoricalOutputFeature.java:31)
	at sklearn.tree.TreeModelUtil$4.apply(TreeModelUtil.java:324)
	at sklearn.tree.TreeModelUtil$4.apply(TreeModelUtil.java:312)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jpmml.converter.Schema.toTransformedSchema(Schema.java:68)
	at sklearn.tree.TreeModelUtil.toTreeModelSchema(TreeModelUtil.java:331)
	at sklearn.tree.TreeModelUtil$3.apply(TreeModelUtil.java:167)
	at sklearn.tree.TreeModelUtil$3.apply(TreeModelUtil.java:163)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at sklearn.tree.TreeModelUtil.encodeTreeModelSegmentation(TreeModelUtil.java:175)
	at sklearn.tree.TreeModelUtil.encodeTreeModelSegmentation(TreeModelUtil.java:154)
	at sklearn.ensemble.gradient_boosting.GradientBoostingUtil.encodeGradientBoosting(GradientBoostingUtil.java:46)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.encodeModel(GradientBoostingClassifier.java:84)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.encodeModel(GradientBoostingClassifier.java:44)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:219)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.ClassCastException: org.jpmml.converter.ContinuousFeature cannot be cast to tpot.builtins.ContinuousOutputFeature
	at tpot.builtins.CategoricalOutputFeature.toContinuousFeature(CategoricalOutputFeature.java:71)
	at tpot.builtins.CategoricalOutputFeature.toContinuousFeature(CategoricalOutputFeature.java:31)
	at sklearn.tree.TreeModelUtil$4.apply(TreeModelUtil.java:324)
	at sklearn.tree.TreeModelUtil$4.apply(TreeModelUtil.java:312)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jpmml.converter.Schema.toTransformedSchema(Schema.java:68)
	at sklearn.tree.TreeModelUtil.toTreeModelSchema(TreeModelUtil.java:331)
	at sklearn.tree.TreeModelUtil$3.apply(TreeModelUtil.java:167)
	at sklearn.tree.TreeModelUtil$3.apply(TreeModelUtil.java:163)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at sklearn.tree.TreeModelUtil.encodeTreeModelSegmentation(TreeModelUtil.java:175)
	at sklearn.tree.TreeModelUtil.encodeTreeModelSegmentation(TreeModelUtil.java:154)
	at sklearn.ensemble.gradient_boosting.GradientBoostingUtil.encodeGradientBoosting(GradientBoostingUtil.java:46)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.encodeModel(GradientBoostingClassifier.java:84)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.encodeModel(GradientBoostingClassifier.java:44)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:219)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
```

My model pipeline using TPOT's StackingEstimator:
```
pmml_pipeline = PMMLPipeline([
    ('features', FeatureUnion([
        ('goods_name_feat',Pipeline([
            ('mapper', DataFrameMapper([('goods_name_split_text',  CountVectorizer(ngram_range=(1, 2), tokenizer=Splitter())),])),
            ('sp', SelectorProxy(SelectPercentile(chi2, percentile=25))),
            ('stacking estimator', StackingEstimator(estimator=LogisticRegression()))
        ])),
        ('goods_desc_feat', Pipeline([
            ('mapper', DataFrameMapper([('goods_desc_split_text',  CountVectorizer(ngram_range=(1, 2), tokenizer=Splitter())),])),
            ('sp', SelectorProxy(SelectPercentile(chi2, percentile=25))),
            ('stacking estimator', StackingEstimator(estimator=LogisticRegression()))
        ])),
#         ('hd_text_feat', Pipeline([
#             ('mapper', DataFrameMapper([('hd_text_split_text',  CountVectorizer(ngram_range=(1, 2), tokenizer=Splitter())),])),
#             ('sp', SelectorProxy(SelectPercentile(chi2, percentile=25))),
#             ('stacking estimator', StackingEstimator(estimator=LogisticRegression()))
#         ])),
#         ('main_text_feat', Pipeline([
#             ('mapper', DataFrameMapper([('main_text_split_text',  CountVectorizer(ngram_range=(1, 2), tokenizer=Splitter())),])),
#             ('sp', SelectorProxy(SelectPercentile(chi2, percentile=25))),
#             ('stacking estimator', StackingEstimator(estimator=LogisticRegression()))
#         ])),
#         ('sku_all_info_feat', Pipeline([
#             ('mapper', DataFrameMapper([('sku_all_info_split_text',  CountVectorizer(ngram_range=(1, 2), tokenizer=Splitter())),])),
#             ('sp', SelectorProxy(SelectPercentile(chi2, percentile=25))),
#             ('stacking estimator', StackingEstimator(estimator=LogisticRegression()))
#         ])),
    ])),
    ('gbdt', GradientBoostingClassifier())
])
```

**Comment by vruusmann** [comment]
@hujiayu The comment about `StackingEstimator` was just a technical observation - meaning that quite a lot of preparatory work has been done, and it wouldn't be too difficult to implement support for `ModelTransformer`.

You should keep using `LogisticRegression` in your pipeline.
