### ISSUE TITLE
XGBClassifier error

### ISSUE THREAD

**Issue by Alexkevin** [jpmml/sklearn2pmml#12]
When I running the following code 
```python
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn2pmml.decoration import ContinuousDomain
import xgboost as xgb

import pandas
import sklearn_pandas

iris = load_iris()

iris_df = pandas.concat((pandas.DataFrame(iris.data[:, :], columns = ["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"]), pandas.DataFrame(iris.target, columns = ["Species"])), axis = 1)

iris_mapper = sklearn_pandas.DataFrameMapper([
    (["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"], [ContinuousDomain(), PCA(n_components = 3),StandardScaler()]),
    ("Species", None)
])

iris = iris_mapper.fit_transform(iris_df)

iris_X = iris[:, 0:3]
iris_y = iris[:, 3]

iris_classifier = xgb.XGBClassifier()
iris_classifier.fit(iris_X, iris_y)

from sklearn2pmml import sklearn2pmml

sklearn2pmml(iris_classifier, iris_mapper, "XGBClassifier.pmml", with_repr = True,debug =True)
```
I got the following error:
```
python:  3.5.1
sklearn:  0.17
sklearn.externals.joblib: 0.9.3
sklearn_pandas:  1.1.0
sklearn2pmml:  0.10.0
java -cp /home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/serpent-1.12.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/jcommander-1.48.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/pmml-agent-1.2.17.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/jaxb-core-2.2.11.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/jpmml-xgboost-1.0.6.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/jaxb-runtime-2.2.11.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/guava-19.0.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/istack-commons-runtime-2.21.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/pyrolite-4.12.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/pmml-schema-1.2.17.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/slf4j-api-1.7.21.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/pmml-model-1.2.17.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/jpmml-sklearn-1.0.0.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/pmml-model-metro-1.2.17.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/slf4j-jdk14-1.7.21.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/jpmml-converter-1.0.8.jar org.jpmml.sklearn.Main --pkl-estimator-input /tmp/estimator-izxjv8gy.pkl.z --repr-estimator XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=1,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='multi:softprob', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1) --pkl-mapper-input /tmp/mapper-wve3iwbh.pkl.z --repr-mapper DataFrameMapper(default=False,
        features=[(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width'], TransformerPipeline(steps=[('continuousdomain', ContinuousDomain(invalid_value_treatment='return_invalid')), ('pca', PCA(copy=True, n_components=3, whiten=False)), ('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True))])), ('Species', None)],
        sparse=False) --pmml-output XGBClassifier.pmml
Sep 01, 2016 12:50:53 PM org.jpmml.sklearn.Main run
INFO: Parsing DataFrameMapper PKL..
Sep 01, 2016 12:50:53 PM org.jpmml.sklearn.Main run
INFO: Parsed DataFrameMapper PKL in 84 ms.
Sep 01, 2016 12:50:53 PM org.jpmml.sklearn.Main run
INFO: Converting DataFrameMapper..
Sep 01, 2016 12:50:53 PM org.jpmml.sklearn.Main run
INFO: Converted DataFrameMapper in 56 ms.
Sep 01, 2016 12:50:53 PM org.jpmml.sklearn.Main run
INFO: Parsing Estimator PKL..
Sep 01, 2016 12:50:53 PM org.jpmml.sklearn.Main run
INFO: Parsed Estimator PKL in 14 ms.
Sep 01, 2016 12:50:53 PM org.jpmml.sklearn.Main run
INFO: Converting Estimator..
Sep 01, 2016 12:50:53 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert Estimator
java.lang.RuntimeException: java.io.IOException
	at xgboost.sklearn.Booster.loadLearner(Booster.java:53)
	at xgboost.sklearn.Booster.getLearner(Booster.java:41)
	at xgboost.sklearn.BoosterUtil.getNumberOfFeatures(BoosterUtil.java:35)
	at xgboost.sklearn.XGBClassifier.getNumberOfFeatures(XGBClassifier.java:38)
	at sklearn.Classifier.createSchema(Classifier.java:59)
	at sklearn.EstimatorUtil.encodePMML(EstimatorUtil.java:47)
	at org.jpmml.sklearn.Main.run(Main.java:189)
	at org.jpmml.sklearn.Main.main(Main.java:107)
Caused by: java.io.IOException
	at org.jpmml.xgboost.XGBoostDataInput.readReserved(XGBoostDataInput.java:68)
	at org.jpmml.xgboost.GBTree.load(GBTree.java:62)
	at org.jpmml.xgboost.Learner.load(Learner.java:88)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:34)
	at xgboost.sklearn.Booster.loadLearner(Booster.java:51)
	... 7 more

Exception in thread "main" java.lang.RuntimeException: java.io.IOException
	at xgboost.sklearn.Booster.loadLearner(Booster.java:53)
	at xgboost.sklearn.Booster.getLearner(Booster.java:41)
	at xgboost.sklearn.BoosterUtil.getNumberOfFeatures(BoosterUtil.java:35)
	at xgboost.sklearn.XGBClassifier.getNumberOfFeatures(XGBClassifier.java:38)
	at sklearn.Classifier.createSchema(Classifier.java:59)
	at sklearn.EstimatorUtil.encodePMML(EstimatorUtil.java:47)
	at org.jpmml.sklearn.Main.run(Main.java:189)
	at org.jpmml.sklearn.Main.main(Main.java:107)
Caused by: java.io.IOException
	at org.jpmml.xgboost.XGBoostDataInput.readReserved(XGBoostDataInput.java:68)
	at org.jpmml.xgboost.GBTree.load(GBTree.java:62)
	at org.jpmml.xgboost.Learner.load(Learner.java:88)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:34)
	at xgboost.sklearn.Booster.loadLearner(Booster.java:51)
	... 7 more
Preserved joblib dump file(s):  /tmp/estimator-izxjv8gy.pkl.z /tmp/mapper-wve3iwbh.pkl.z
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-94-3559b9c97359> in <module>()
----> 1 sklearn2pmml(iris_classifier, iris_mapper, "XGBClassifier.pmml", with_repr = True,debug =True)

/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(estimator, mapper, pmml, with_repr, debug)
     63                 if(debug):
     64                         print(" ".join(cmd))
---> 65                 subprocess.check_call(cmd)
     66         finally:
     67                 if(debug):

/home/shuangyangwang/anaconda3/lib/python3.5/subprocess.py in check_call(*popenargs, **kwargs)
    582         if cmd is None:
    583             cmd = popenargs[0]
--> 584         raise CalledProcessError(retcode, cmd)
    585     return 0
    586 

CalledProcessError: Command '['java', '-cp', '/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/serpent-1.12.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/jcommander-1.48.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/pmml-agent-1.2.17.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/jaxb-core-2.2.11.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/jpmml-xgboost-1.0.6.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/jaxb-runtime-2.2.11.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/guava-19.0.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/istack-commons-runtime-2.21.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/pyrolite-4.12.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/pmml-schema-1.2.17.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/slf4j-api-1.7.21.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/pmml-model-1.2.17.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/jpmml-sklearn-1.0.0.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/pmml-model-metro-1.2.17.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/slf4j-jdk14-1.7.21.jar:/home/shuangyangwang/anaconda3/lib/python3.5/site-packages/sklearn2pmml/resources/jpmml-converter-1.0.8.jar', 'org.jpmml.sklearn.Main', '--pkl-estimator-input', '/tmp/estimator-izxjv8gy.pkl.z', '--repr-estimator', "XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=1,\n       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=3,\n       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,\n       objective='multi:softprob', reg_alpha=0, reg_lambda=1,\n       scale_pos_weight=1, seed=0, silent=True, subsample=1)", '--pkl-mapper-input', '/tmp/mapper-wve3iwbh.pkl.z', '--repr-mapper', "DataFrameMapper(default=False,\n        features=[(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width'], TransformerPipeline(steps=[('continuousdomain', ContinuousDomain(invalid_value_treatment='return_invalid')), ('pca', PCA(copy=True, n_components=3, whiten=False)), ('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True))])), ('Species', None)],\n        sparse=False)", '--pmml-output', 'XGBClassifier.pmml']' returned non-zero exit status 1
```

how to deal with that?

**Comment by Alexkevin** [comment]
I also tried the command line to convert that ,but failed

d:\Users\shuangyangwang\Desktop\jpmml-sklearn-master\target>java -jar converter-
executable-1.1-SNAPSHOT.jar --pkl-mapper-input mapper.pkl --pkl-estimator-input
estimator.pkl --pmml-output mapper-estimator.pmml

九月 01, 2016 1:24:48 下午 org.jpmml.sklearn.Main run
信息: Parsing DataFrameMapper PKL..
九月 01, 2016 1:24:48 下午 org.jpmml.sklearn.Main run
信息: Parsed DataFrameMapper PKL in 39 ms.
九月 01, 2016 1:24:48 下午 org.jpmml.sklearn.Main run
信息: Converting DataFrameMapper..
九月 01, 2016 1:24:48 下午 org.jpmml.sklearn.Main run
信息: Converted DataFrameMapper in 30 ms.
九月 01, 2016 1:24:48 下午 org.jpmml.sklearn.Main run
信息: Parsing Estimator PKL..
九月 01, 2016 1:24:48 下午 org.jpmml.sklearn.Main run
信息: Parsed Estimator PKL in 1 ms.

Exception in thread "main" java.lang.IllegalArgumentException: The estimator obj
ect (Python class xgboost.XGBClassifier) is not an Estimator or is not a support
ed Estimator subclass
        at org.jpmml.sklearn.Main.run(Main.java:180)
        at org.jpmml.sklearn.Main.main(Main.java:107)

**Comment by vruusmann** [comment]
This looks related to https://github.com/jpmml/jpmml-sklearn/issues/16

In brief, XGBoost has changed something about its serialization mechanism/data format between `0.4` and `0.6` versions.

What is your XGBoost version?

**Comment by vruusmann** [comment]
Specifically, JPMML-XGBoost library was expecting to read a zero byte, but got a non-zero byte:
```
Caused by: java.io.IOException
    at org.jpmml.xgboost.XGBoostDataInput.readReserved(XGBoostDataInput.java:68)
```

**Comment by Alexkevin** [comment]
Thanks for response
I tried to use both version 0.4 and 0.6 ,but all failed

Do you have any suggestion about non-zero byte error?  I have no idea about it

**Comment by vruusmann** [comment]
You could simply comment out the line `throw new IOException()` in the `XGBoostDataInput#readReserved(XGBoostDataInput)` method.

Zero bytes were meant to represent "unused" space. However, looks like newer XGBoost versions are using this previously "unused" space for something. I don't know if this new information is relevant or not from the PMML perspective. Maybe it will be OK to ignore those new non-zero bytes, maybe not.

Could you attach your XGBoost binary file to this issue? I would take a look at it myself, and try to figure out what's the change.

**Comment by Alexkevin** [comment]
Couldn't attach files
But I email them to you ~

**Comment by Alexkevin** [comment]
[You could get it here](https://github.com/Alexkevin/Ctripmml)

**Comment by Alexkevin** [comment]
unfortunately, even though I comment out the code , the same errors still happen

**Comment by vruusmann** [comment]
Your code (as given in the first comment of this issue) runs fine:
```
python:  3.4.3
sklearn:  0.18.dev0
sklearn.externals.joblib: 0.9.4
sklearn_pandas:  1.1.0
sklearn2pmml:  0.11.0
xgboost: 0.6
```

**Comment by vruusmann** [comment]
Turns out that XGBoost `0.6` uses the first value of the previously "unused" space to indicate if the `Learner` object has extra attributes attached to it.

The JPMML-XGBoost library has now been brought up-to-date with this change: https://github.com/jpmml/jpmml-xgboost/commit/ec4bdc669d625dabb34fd63ae24f516d1092428c
