### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by zhangjunqiang** [jpmml/sklearn2pmml#123]
Standard output is empty
Standard error:
Dec 21, 2018 4:59:26 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Dec 21, 2018 4:59:26 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 84 ms.
Dec 21, 2018 4:59:26 PM org.jpmml.sklearn.Main run
INFO: Converting..
Dec 21, 2018 4:59:26 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:51)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:202)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:51)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:202)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

**Comment by vruusmann** [comment]
> java.lang.IllegalArgumentException
>  at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:51)

This stack trace elements points here:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn_pandas/DataFrameMapper.java#L51

In brief, the value of the `DataFrameMapper.default` attribute must be `False`. Other values are not supported at the moment.

Keeping this issue open as a remainder to improve exception messages.
