### ISSUE TITLE
Error running the DecisionTree example code

### ISSUE THREAD

**Issue by minhduc0711** [jpmml/sklearn2pmml#127]
I'm trying to run the example code in the README
```python
import pandas

iris_df = pandas.read_csv("Iris.csv")

from sklearn.tree import DecisionTreeClassifier
from sklearn2pmml.pipeline import PMMLPipeline

pipeline = PMMLPipeline([
	("classifier", DecisionTreeClassifier())
])
pipeline.fit(iris_df[iris_df.columns.difference(["Species"])], iris_df["Species"])

from sklearn2pmml import sklearn2pmml

sklearn2pmml(pipeline, "DecisionTreeIris.pmml", with_repr = True)
```
but I got this error
```
SEVERE: Failed to parse PKL
net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for numpy.core._multiarray_umath._reconstruct)
        at net.razorvine.pickle.objects.ClassDictConstructor.construct(ClassDictConstructor.java:23)
        at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:732)
        at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:200)
        at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
        at numpy.core.NDArrayUtil.readObject(NDArrayUtil.java:384)
        at numpy.core.NDArrayUtil.access$700(NDArrayUtil.java:42)
        at numpy.core.NDArrayUtil$TypeDescriptor.read(NDArrayUtil.java:542)
        at numpy.core.NDArrayUtil.parseArray(NDArrayUtil.java:215)
        at numpy.core.NDArrayUtil.parseData(NDArrayUtil.java:190)
        at joblib.NumpyArrayWrapper.toArray(NumpyArrayWrapper.java:43)
        at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:88)
        at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
        at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)
        at org.jpmml.sklearn.Main.run(Main.java:104)
        at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for numpy.core._multiarray_umath._reconstruct)
        at net.razorvine.pickle.objects.ClassDictConstructor.construct(ClassDictConstructor.java:23)
        at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:732)
        at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:200)
        at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
        at numpy.core.NDArrayUtil.readObject(NDArrayUtil.java:384)
        at numpy.core.NDArrayUtil.access$700(NDArrayUtil.java:42)
        at numpy.core.NDArrayUtil$TypeDescriptor.read(NDArrayUtil.java:542)
        at numpy.core.NDArrayUtil.parseArray(NDArrayUtil.java:215)
        at numpy.core.NDArrayUtil.parseData(NDArrayUtil.java:190)
        at joblib.NumpyArrayWrapper.toArray(NumpyArrayWrapper.java:43)
        at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:88)
        at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
        at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)
        at org.jpmml.sklearn.Main.run(Main.java:104)
        at org.jpmml.sklearn.Main.main(Main.java:94)
```
Can anyone help me? Thanks.

**Comment by vruusmann** [comment]
> Exception in thread "main" net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for numpy.core._multiarray_umath._reconstruct)

The pickled `PMMLPipeline` object graph contains CPython object `numpy.core._multiarray_umath._reconstruct`. It's not supposed to be there, hence the exception.

This example code executes cleanly in my computer, which means that there's some package version incompatibility (maybe this CPython class is being mandatory in newer Pandas package versions). Please re-run the example with debugging enabled (`sklearn2pmml(.., debug = True)`, and paste the package version information here.

**Comment by vruusmann** [comment]
> Here are my packages

Thanks. For reference, these are my packages, which work well with the above code example:
```
python: 3.4.3
sklearn: 0.20.1
sklearn.externals.joblib: 0.13.0
pandas: 0.22.0
sklearn_pandas: 1.7.0
sklearn2pmml: 0.39.0
openjdk: 1.8.0_111
```

Will upgrade my Pandas package version from 0.22(.0) to 0.23(.4) later today, and see if it breaks anything.
