### ISSUE TITLE
Error : (Python class sklearn_pandas.transformers.CategoricalImputer) is not a supported Transformer

### ISSUE THREAD

**Issue by Simbamoureux** [jpmml/sklearn2pmml#128]
Hello,

Today while trying to create a PMML I stumbled upon this issue : 

```
Exception in thread "main" java.lang.IllegalArgumentException: The value object (Python class sklearn_pandas.transformers.CategoricalImputer) is not a supported Transformer
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:616)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:72)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:202)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.base/java.lang.Class.cast(Class.java:3606)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 8 more
```

I find this weird because it is specified in the README of the jpmml-sklearn package that sklearn-pandas' CategoricalImputer is supported.

Any idea why I could get this error ?

Here are my packages versions : 

```
python: 3.6.6
sklearn: 0.20.2
sklearn.externals.joblib: 0.13.0
pandas: 0.23.4
sklearn_pandas: 1.8.0
sklearn2pmml: 0.40.0
openjdk: 11.0.1
```

Thanks for the help !

**Comment by vruusmann** [comment]
> I find this weird because it is specified in the README of the jpmml-sklearn package that sklearn-pandas' CategoricalImputer is supported.

It is supported. However, the JPMML-SkLearn class thinks that the fully qualified name of this class should be `sklearn_pandas.categorical_imputer.CategoricalImputer`, not `sklearn_pandas.transformers.CategoricalImputer`:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/resources/META-INF/sklearn2pmml.properties#L147

Looks like this class has been moved to a different module between `sklearn_pandas` package versions 1.7 and 1.8.

The solution is to add an "alias" into this "Python class" to "JPMML-SkLearn converter class" mappings file.

**Comment by Simbamoureux** [comment]
Hello,

It indeed fixed the issue to switch to sklearn-pandas 1.7.0.

Consider adding "recommended package versions" in the README to avoid confusion, I indeed had a hunch that the problem would lie around package version issues.

Thanks for the help and quick response, I'm closing the issue.

**Comment by vruusmann** [comment]
I'm reopening this issue, because the SkLearn2PMML/JPMML-SkLearn stack should support all `sklearn_pandas` package versions, not just an arbitrary one.

For me, it's a very easy fix - need to add a one new mapping into the `sklearn2pmml.properties` file.

An updated SkLearn2PMML package (works both with `sklearn_pandas` versions 1.7 and 1.8) should be available early next week.

**Comment by lampda** [comment]
I had same problem with `sklearn2pmml: 0.69.0` and `sklearn_pandas:2.1.0`

```python

class CustLE(LabelEncoder):
    def __init__(self, dict_mapping):
        super(LabelEncoder,self).__init__()
        self.dict_mapping = dict_mapping

    def transform(self, y):
        y = pd.Series(y).map(self.dict_mapping)
        return y

    def fit_transform(self, y):
        return self.transform(y)
```

While trying to save my pipeline, I got errors:
```js
Standard output is empty
Standard error:
Apr 06, 2021 2:37:15 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Apr 06, 2021 2:37:15 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 22 ms.
Apr 06, 2021 2:37:15 PM org.jpmml.sklearn.Main run
INFO: Converting PKL to PMML..
Apr 06, 2021 2:37:15 PM sklearn2pmml.pipeline.PMMLPipeline initTargetFields
WARNING: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
Apr 06, 2021 2:37:15 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert PKL to PMML
java.lang.IllegalArgumentException: The value object (Python class __main__.CustLE) is not a supported Transformer
	at org.jpmml.python.CastFunction.apply(CastFunction.java:45)
	at sklearn_pandas.DataFrameMapper.getTransformerList(DataFrameMapper.java:169)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:71)
	at sklearn.Initializer.encodeFeatures(Initializer.java:48)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:212)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:43)
	... 8 more

Exception in thread "main" java.lang.IllegalArgumentException: The value object (Python class __main__.CustLE) is not a supported Transformer
	at org.jpmml.python.CastFunction.apply(CastFunction.java:45)
	at sklearn_pandas.DataFrameMapper.getTransformerList(DataFrameMapper.java:169)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:71)
	at sklearn.Initializer.encodeFeatures(Initializer.java:48)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:212)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:43)
	... 8 more
```
