### ISSUE TITLE
columnTransformer passthrough/drop error

### ISSUE THREAD

**Issue by xiaowei1234** [jpmml/sklearn2pmml#135]
ColumnTransformer is a fairly new sklearn feature so I expect not everything will be working. I believe I have encountered an error with sklearn2pmml conversion.

Here is a columnTransformer step that drops the first column of the input
`col_trans2 = ColumnTransformer([('last', 'drop', [0])], remainder='passthrough')`

Here is the entire pipeline
```
pl = PMMLPipeline([
    ('one', wrap)
    , ('two', col_trans2)
    , ('clf', LogisticRegression())
])
```

The pipeline runs fine when executing `pl.fit`. However, when I do sklearn2pmml on the pipeline it returns an error. The line runs fine when I comment out the `('two', col_trans2)` step

```
Feb 22, 2019 2:08:12 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: The estimator object (Java class java.lang.String) is not a supported Transformer
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at sklearn.compose.ColumnTransformer.getTransformer(ColumnTransformer.java:115)
	at sklearn.compose.ColumnTransformer.encodeFeatures(ColumnTransformer.java:62)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:198)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast java.lang.String to sklearn.Transformer
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 6 more

Exception in thread "main" java.lang.IllegalArgumentException: The estimator object (Java class java.lang.String) is not a supported Transformer
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at sklearn.compose.ColumnTransformer.getTransformer(ColumnTransformer.java:115)
	at sklearn.compose.ColumnTransformer.encodeFeatures(ColumnTransformer.java:62)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:198)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast java.lang.String to sklearn.Transformer
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 6 more
```

**Comment by vruusmann** [comment]
Fixed in https://github.com/jpmml/jpmml-sklearn/commit/29b7cc313490707b52cd830d641a24d1a75e3016
