### ISSUE TITLE
Detect and warn about unnecessary PMMLPipeline nesting

### ISSUE THREAD

**Issue by xiaowei1234** [jpmml/sklearn2pmml#138]
Hi Villu,

I am running into an error when running sklearn2pmml using the following code. The preprocessing code transforms the data fine but it's giving me a weird error.

```
import pandas as pd
import numpy as np
from sklearn_pandas import DataFrameMapper
from sklearn2pmml.decoration import ContinuousDomain
from sklearn2pmml import PMMLPipeline, sklearn2pmml
from sklearn.pipeline import FeatureUnion
from sklearn.linear_model import LogisticRegression
from sklearn2pmml.preprocessing import LookupTransformer, ExpressionTransformer


manual_df = pd.DataFrame({'code1': [99, 99, 5], 'code2': [-1, -1, 5], 'other': [1,2,3]})
y = np.array([0,0,1])
other = DataFrameMapper([(['other'], ContinuousDomain())])
look = DataFrameMapper([
    ('code1', LookupTransformer({5: 1}, 0))
    , ('code2', LookupTransformer({5: 1}, 0))
])
express = ExpressionTransformer('X[0]+X[1]')

look_express = PMMLPipeline([('look', look), ('express', express)])

fu = FeatureUnion([
 ('feat1', other)
, ('feat2', look_express)
])

pipe = PMMLPipeline([
    ('fu', fu)
    , ('clf', LogisticRegression())
])
xpipe = PMMLPipeline([
     ('fu', fu)
])
```

fit works fine
```
pipe.fit(manual_df, y)
man_x = xpipe.fit_transform(manual_df)
```

but when I try to `sklearn2pmml(pipe, 'trial.pmml', with_repr=True)`

I get 
```
Standard output is empty
Standard error:
Mar 12, 2019 3:24:01 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Mar 12, 2019 3:24:01 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 31 ms.
Mar 12, 2019 3:24:01 PM org.jpmml.sklearn.Main run
INFO: Converting..
Mar 12, 2019 3:24:01 PM sklearn2pmml.pipeline.PMMLPipeline encodePMML
WARNING: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
Mar 12, 2019 3:24:01 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: Expected 2 element(s), got 3 element(s)
	at org.jpmml.sklearn.ClassDictUtil.checkSize(ClassDictUtil.java:63)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:210)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException: Expected 2 element(s), got 3 element(s)
	at org.jpmml.sklearn.ClassDictUtil.checkSize(ClassDictUtil.java:63)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:210)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-89-e98c852857fb> in <module>()
----> 1 sklearn2pmml(pipe, 'trial.pmml', with_repr=True)

~/anaconda3/lib/python3.6/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    250                                 print("Standard error is empty")
    251                 if retcode:
--> 252                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    253         finally:
    254                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

**Comment by vruusmann** [comment]
> other = DataFrameMapper([(['other', ContinuousDomain()])])

The DataFrameMapper transform is supposed to contain a list of tuples, where each tuple contains at least two elements `(feature name, transformer(s))`.

You have a single-element tuple there. Don't know why Scikit-Learn is accepting such thing, when it's clearly a violation of DataFrameMapper specification.

**Comment by xiaowei1234** [comment]
O man, sorry, I was trying to make an easy to reproducible example with a tiny dataframe and made this error. Let me edit my answer

**Comment by vruusmann** [comment]
> Let me edit my answer

And please add imports as well! I hate typing those myself.

**Comment by xiaowei1234** [comment]
ah sorry let me do that too

**Comment by xiaowei1234** [comment]
updated with imports. The error seems to be some kind of mismatch between the data dimensions and what java thinks are the dimensions

**Comment by vruusmann** [comment]
> look_express = PMMLPipeline([('look', look), ('express', express)])

On this line, replace `PMMLPipeline` with regular Scikit-Learn pipeline, and your demo converts successfully.

The lesson is that you should use `PMMLPipeline` only at the outermost "level". Use regular Scikit-Learn at all other levels.

**Comment by vruusmann** [comment]
Let's keep this issue open as a reminder that JPMML-SkLearn should throw an IllegalArgumentException("Use Pipeline instead of PMMLPipeline in this location") whenever it finds a nested PMMLPipeline object.

**Comment by xiaowei1234** [comment]
many thanks!
