### ISSUE TITLE
Support for `TruncatedSVD` transformation type

### ISSUE THREAD

**Issue by zdx** [jpmml/sklearn2pmml#141]
python: 3.6.8
sklearn: 0.18.1
sklearn.externals.joblib: 0.10.3
pandas: 0.24.1
sklearn_pandas: 1.8.0
sklearn2pmml: 0.43.0
java: 1.8.0_191

code: 
    source_data = pd.read_csv(filePath).head(100)
    source_data['seg_words'] = source_data['content'].astype(str).apply(cut_word)
    ##  tf-idf
    x_train = source_data['seg_words']
    y_train = source_data['a.category']
    vectorizer = TfidfVectorizer(max_features=100000, norm=None, ngram_range=(1, 2), min_df=3, max_df=0.9, sublinear_tf=True, tokenizer=Splitter())
 
    ##  lsa
    lsa = TruncatedSVD(n_components=200)

    ## classfier
    clf = LinearSVC(penalty='l2', dual=True)

    idf_vec = vectorizer.fit_transform(x_train, y_train)
    lsa_f = lsa.fit_transform(idf_vec)
    clf.fit(lsa_f, y_train)
    pipeline = Pipeline([
        ("tf-idf", vectorizer),
        ("lsa", lsa),
        ("classifier", LinearSVC(penalty='l2', dual=True))
    ])
    pipeline.fit(x_train, y_train)
    from sklearn2pmml import make_pmml_pipeline
    pipeline_pmml = make_pmml_pipeline(pipeline, active_fields=['seg_words'], target_fields=['a.category'])
    pipeline_pmml.fit(x_train, y_train)
    sklearn2pmml(pipeline_pmml, "Line_SVM_Classifier.pmml", with_repr=False, debug=True)

error: 

??: Failed to convert
java.lang.IllegalArgumentException: Tuple contains an unsupported value (Python class sklearn.decomposition.truncated_svd.TruncatedSVD)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:616)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:68)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:198)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 6 more

**Comment by vruusmann** [comment]
Noted, but unsure if this transformation type is worth supporting at all.

PMML is not intended for large-scale matrix multiplication use cases. Perhaps it will be possible to extract `TruncatedSVD` component values, and then merge them into subsequent `LinearSVC` coefficient values.
