### ISSUE TITLE
Improve the naming of derived fields

### ISSUE THREAD

**Issue by xiaowei1234** [jpmml/sklearn2pmml#143]
Is it intentional to throw an illegal argument error when the same variable is used more than once using LookUpTransformer? See below for example:

```
import pandas as pd
import numpy as np
from sklearn_pandas import DataFrameMapper
from sklearn2pmml.decoration import ContinuousDomain
from sklearn2pmml import PMMLPipeline, sklearn2pmml
from sklearn.pipeline import FeatureUnion
from sklearn.linear_model import LogisticRegression
from sklearn2pmml.preprocessing import LookupTransformer, ExpressionTransformer, PMMLLabelBinarizer
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

manual_df = pd.DataFrame({'code1': ['a', 'b', 'c'], 'code2': [-1, -2, 5], 'other': [1,2,3]})
y = np.array([0,0,1])
other = DataFrameMapper([(['other'], ContinuousDomain())])
lk_pipe = LookupTransformer({'a': 1, 'b': 1}, 0)
look = DataFrameMapper([
    (['code1'], lk_pipe)
    ,(['code1'], LookupTransformer({'c': 3}, 0))
])


pipe = PMMLPipeline([
    ('lk', look)
#     , ('imp', SimpleImputer(strategy='median'))
    , ('sd', StandardScaler())
    , ('clf', LogisticRegression())
])

pipe.fit(manual_df, y)
sklearn2pmml(pipe, 'trial.pmml', with_repr=True)
```

error message
```
Standard output is empty
Standard error:
Mar 15, 2019 3:39:51 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Mar 15, 2019 3:39:51 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 25 ms.
Mar 15, 2019 3:39:51 PM org.jpmml.sklearn.Main run
INFO: Converting..
Mar 15, 2019 3:39:51 PM sklearn2pmml.pipeline.PMMLPipeline encodePMML
WARNING: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
Mar 15, 2019 3:39:51 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: lookup(code1)
	at org.jpmml.converter.PMMLEncoder.checkName(PMMLEncoder.java:270)
	at org.jpmml.converter.PMMLEncoder.addDerivedField(PMMLEncoder.java:150)
	at org.jpmml.converter.PMMLEncoder.createDerivedField(PMMLEncoder.java:160)
	at sklearn2pmml.preprocessing.LookupTransformer.encodeFeatures(LookupTransformer.java:105)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:198)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException: lookup(code1)
	at org.jpmml.converter.PMMLEncoder.checkName(PMMLEncoder.java:270)
	at org.jpmml.converter.PMMLEncoder.addDerivedField(PMMLEncoder.java:150)
	at org.jpmml.converter.PMMLEncoder.createDerivedField(PMMLEncoder.java:160)
	at sklearn2pmml.preprocessing.LookupTransformer.encodeFeatures(LookupTransformer.java:105)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:198)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-76-e98c852857fb> in <module>()
----> 1 sklearn2pmml(pipe, 'trial.pmml', with_repr=True)

~/anaconda3/lib/python3.6/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    250                                 print("Standard error is empty")
    251                 if retcode:
--> 252                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    253         finally:
    254                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

**Comment by vruusmann** [comment]
In PMML derived fields are identified by name. The SkLearn2PMML/JPMML-SkLearn stack uses a convention, where the name is auto-generated using a formula `<function name>(<argument names>)`.

In your case, you are applying `LookupTransformer` twice to the same feature, which is about to give rise to two `lookup(<argument name>)` derived fields. This cannot be let to happen.

In addition to rearranging the pipeline, you might try renaming derived fields using the `sklearn.decoration.Alias` pseudo-transformer:
https://github.com/jpmml/sklearn2pmml/blob/master/sklearn2pmml/decoration/__init__.py#L8-L26

```python
mapper = DataFrameMapper([
  ("column", Alias(LookupTransformer({..}), "lk_1", prefit = True)),
  ("column", Alias(LookupTransformer({..}), "lk_2", prefit = True))
])
```

The resulting PMML document should now contain two `DerivedField` elements "lk_1" and "lk_2" (instead of a duplicate element "lookup(column)"), and the name clash is avoided.

Please note that when using `LookupTransformer`, you need to specify `Alias(.., prefit = True)`, as the transformer is parameterized "externally" using a dict.

**Comment by xiaowei1234** [comment]
ah thanks so much

**Comment by vruusmann** [comment]
A workaround: the converter should try a more helpful exception when there is an attempt to declare a duplicate derived field. Specifically, the converter should point out that the `sklearn2pmml.decoration.Alias` meta-transformation can used to "override" the default name.

A fix: the converter should append a "disambiguation suffix" to problematic field names. So far, the convention has been to use a `@<integer>` suffix, but something else might be more pleasing to the eye (perhaps `(<integer>)` suffix).

When the converter performs an automatic rename, then it might still inform the end user that he/she should probably take care of it explicitly. Something like: `field <initial name> was automatically renamed to `<final name>`; use the Alias decoration to specify a better name`.
