### ISSUE TITLE
cutTransformer bin/label arguments doesn't accept numpy datatypes

### ISSUE THREAD

**Issue by xiaowei1234** [jpmml/sklearn2pmml#145]
Hi Villu,

This time I managed to figure it out on my own. The problem is that for CutTransformer sklearn2pmml will only accept an iterable that is the generic Python float/int datatypes and will error when the numbers are numpy datatypes e.g. np.int64/float64 etc.

See below, you can experiment by switching between `bin_array_float` and `bin_python`

```
import pandas as pd
import numpy as np
from sklearn_pandas import DataFrameMapper
from sklearn2pmml.decoration import ContinuousDomain
from sklearn2pmml import PMMLPipeline, sklearn2pmml
from sklearn.pipeline import FeatureUnion
from sklearn.linear_model import LogisticRegression
from sklearn2pmml.preprocessing import LookupTransformer\
, ExpressionTransformer, PMMLLabelBinarizer, CutTransformer
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, FunctionTransformer

manual_df = pd.DataFrame({'code1': [463., 600., 961.], 'code2': [-1, -1, 5], 'other': [1,2,3]})
y = np.array([0,0,1])
other = DataFrameMapper([(['other'], ContinuousDomain())])
aac = ContinuousDomain(
    missing_value_replacement=801.
                         , outlier_treatment='as_extreme_values'
                       , missing_value_treatment='as_value'
                      , low_value=0., high_value=961.)

bin_lst_mixed = [-902.0, -900.0, 723.0, 771.0, 869.0, 898.0, 9999999]
bin_array_float = np.float64(bin_lst_mixed)
bin_python = [-902.0, -900.0, 723.0, 771.0, 869.0, 898.0, 9999999.]

bins = [aac,
        FunctionTransformer(np.square)
        , CutTransformer(bins=bin_array_float,
              include_lowest=True,
              labels=[0.00753726788203926, 0.0580498294063001, 1.00545556247853, 0.0167485649980225, 0.616619727092687, 0.197904575935953],
              right=True)
       ]

look = DataFrameMapper([
        (['code1'], bins)
    , ('code2', LookupTransformer({5: 1}, 0))
])
# express = ExpressionTransformer('X[0]+X[1]')

# look_express = make_pipeline(look, express)

fu = FeatureUnion([
 ('feat1', other)
, ('feat2', look)
])

pipe = PMMLPipeline([
    ('fu', fu)
#     , ('imp', SimpleImputer(strategy='median'))
    , ('clf', LogisticRegression())
])
xpipe = PMMLPipeline([
     ('fu', fu)
])

pipe.fit(manual_df, y)
man_x = xpipe.fit_transform(manual_df)

sklearn2pmml(pipe, 'trial.pmml', with_repr=True)
```

error message when using numpy datatype
```
Standard output is empty
Standard error:
Mar 18, 2019 1:18:10 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Mar 18, 2019 1:18:10 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 35 ms.
Mar 18, 2019 1:18:10 PM org.jpmml.sklearn.Main run
INFO: Converting..
Mar 18, 2019 1:18:10 PM sklearn2pmml.pipeline.PMMLPipeline encodePMML
WARNING: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
Mar 18, 2019 1:18:10 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: Attribute 'sklearn2pmml.preprocessing.CutTransformer.bins' has an unsupported value (Python class numpy.ndarray)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at org.jpmml.sklearn.PyClassDict.get(PyClassDict.java:56)
	at org.jpmml.sklearn.PyClassDict.getList(PyClassDict.java:174)
	at org.jpmml.sklearn.PyClassDict.getList(PyClassDict.java:178)
	at sklearn2pmml.preprocessing.CutTransformer.getBins(CutTransformer.java:113)
	at sklearn2pmml.preprocessing.CutTransformer.encodeFeatures(CutTransformer.java:49)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.pipeline.FeatureUnion.encodeFeatures(FeatureUnion.java:47)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:198)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast numpy.core.NDArray to java.util.List
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 12 more

Exception in thread "main" java.lang.IllegalArgumentException: Attribute 'sklearn2pmml.preprocessing.CutTransformer.bins' has an unsupported value (Python class numpy.ndarray)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at org.jpmml.sklearn.PyClassDict.get(PyClassDict.java:56)
	at org.jpmml.sklearn.PyClassDict.getList(PyClassDict.java:174)
	at org.jpmml.sklearn.PyClassDict.getList(PyClassDict.java:178)
	at sklearn2pmml.preprocessing.CutTransformer.getBins(CutTransformer.java:113)
	at sklearn2pmml.preprocessing.CutTransformer.encodeFeatures(CutTransformer.java:49)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.pipeline.FeatureUnion.encodeFeatures(FeatureUnion.java:47)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:198)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast numpy.core.NDArray to java.util.List
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 12 more

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-e98c852857fb> in <module>()
----> 1 sklearn2pmml(pipe, 'trial.pmml', with_repr=True)

~/anaconda3/lib/python3.6/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    250                                 print("Standard error is empty")
    251                 if retcode:
--> 252                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    253         finally:
    254                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

**Comment by vruusmann** [comment]
You managed to find this weakness, because your code is generating bin values programmatically, using numpy functions. If you were specifying them manually, then you'd probably use regular lists `[]` instead of Numpy arrays (and the problem wouldn't happen).

This issue probably affect several other transformers too.

**Comment by xiaowei1234** [comment]
Ah I see, maybe it would make sense for sklearn2pmml to raise an error when numpy datatypes are used instead of Python datatypes

**Comment by vruusmann** [comment]
> .. raise an error telling the user to use Python int/float when numpy datatypes are used

It's probably less work to implement Numpy array support in the Java side (than add attribute checks everywhere in the Python side). Just need to declare some utility method and filter all "iterable-like" attributes though it.
