### ISSUE TITLE
Add support for sklearn 0.21

### ISSUE THREAD

**Issue by sam-s** [jpmml/sklearn2pmml#154]
As described in https://github.com/jpmml/jpmml-sklearn/issues/103 and https://github.com/openscoring/openscoring/issues/49:
```
Standard error:
May 20, 2019 12:33:04 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
May 20, 2019 12:33:04 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 58 ms.
May 20, 2019 12:33:04 PM org.jpmml.sklearn.Main run
INFO: Converting..
May 20, 2019 12:33:04 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: Attribute 'sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.loss_' has an unsupported value (Python class sklearn.ensemble._gb_losses.BinomialDeviance)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at org.jpmml.sklearn.PyClassDict.get(PyClassDict.java:57)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.getLoss(GradientBoostingClassifier.java:121)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.encodeModel(GradientBoostingClassifier.java:67)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.encodeModel(GradientBoostingClassifier.java:42)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:213)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.ensemble.gradient_boosting.LossFunction
	at java.base/java.lang.Class.cast(Class.java:3611)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 7 more

Exception in thread "main" java.lang.IllegalArgumentException: Attribute 'sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.loss_' has an unsupported value (Python class sklearn.ensemble._gb_losses.BinomialDeviance)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at org.jpmml.sklearn.PyClassDict.get(PyClassDict.java:57)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.getLoss(GradientBoostingClassifier.java:121)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.encodeModel(GradientBoostingClassifier.java:67)
	at sklearn.ensemble.gradient_boosting.GradientBoostingClassifier.encodeModel(GradientBoostingClassifier.java:42)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:213)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.ensemble.gradient_boosting.LossFunction
	at java.base/java.lang.Class.cast(Class.java:3611)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 7 more
```

**Comment by vruusmann** [comment]
Fixed in https://github.com/jpmml/jpmml-sklearn/commit/f6fceb8dc6c78fb17acc8dcde515c70f7d9813ec

The JPMML-SkLearn code repository contains all the necessary code changes. However, there hasn't been a JPMML-SkLearn release yet (and consequently, no SkLearn2PMML release either).

**Comment by sam-s** [comment]
okay, so how do I get notified that there is a release fixing this bug?
thanks

**Comment by vruusmann** [comment]
> how do I get notified that there is a release fixing this bug?

Be a "watcher" of the project

**Comment by sam-s** [comment]
I still see this error with `sklearn2pmml-0.46.0`

**Comment by vruusmann** [comment]
> I still see this error with sklearn2pmml-0.46.0

Impossible:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/resources/META-INF/sklearn2pmml.properties#L37
