### ISSUE TITLE
0.21 SimpleImputer not working?

### ISSUE THREAD

**Issue by xiaowei1234** [jpmml/sklearn2pmml#155]
Hey Villu,

The latest sklearn version 0.21 SimpleImputer transformation doesn't seem to be supported currently. I downgraded to sklearn v0.20.3 and it works

error below:

```
java.lang.IllegalArgumentException: Tuple contains an unsupported value (Python class sklearn.impute._base.SimpleImputer)
        at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
        at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:616)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
        at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:68)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:198)
        at org.jpmml.sklearn.Main.run(Main.java:145)
        at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
        at java.lang.Class.cast(Class.java:3369)
        at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
6 more

Exception in thread "main" java.lang.IllegalArgumentException: Tuple contains an unsupported value (Python class sklearn.impute._base.SimpleImputer)
        at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
        at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:616)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
        at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:68)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:198)
        at org.jpmml.sklearn.Main.run(Main.java:145)
        at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
        at java.lang.Class.cast(Class.java:3369)
        at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
6 more
```

**Comment by vruusmann** [comment]
All SkLearn2PMML/JPMML-SkLearn integration tests have been upgraded to Scikit-Learn 0.21(.1): https://github.com/jpmml/jpmml-sklearn/commit/f6fceb8dc6c78fb17acc8dcde515c70f7d9813ec

Among other things, there's a new mapping for the relocated `SimpleImputer` class:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/resources/META-INF/sklearn2pmml.properties#L80-L81

If you're working with Scikit-Learn 0.21, then you need to upgrade to SkLearn2PMML version 0.45.0 (or greater) - it was released earlier today.
