### ISSUE TITLE
PMMLPipeline works fine but sklearn2PMML  results in error.

### ISSUE THREAD

**Issue by nedhulseman** [jpmml/sklearn2pmml#158]
I am trying to output model and pipeline to pmml. After running the PMMLpipeline everything works including pipeline.predict_proba(X) etc. But when I try to output to PMML I get error at line 43. Would you be able to provide any guidance?

Thank you so much in advanced.

model = XGBClassifier()

mapper = DataFrameMapper([
    (["Company"], LabelBinarizer()),
    (["State"],LabelBinarizer()),
    (["Product"], LabelBinarizer()),
    (["Sub-product"], LabelBinarizer()),
    (["Issue"], LabelBinarizer()),
    (["Sub-issue"], LabelBinarizer()),
    (list(range(0, 100)), None)#,
    #("group_response", None)
])

pipeline = PMMLPipeline([
    ("mapper",mapper),
    ("classifier", model)
])

pipeline.fit(df_clean_na,   df_clean_na["group_response"])
sklearn2pmml(pipeline, "prioritize.pmml", with_repr=True)

This results in the error:

Standard output is empty
Standard error:
Jun 05, 2019 2:05:43 AM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Jun 05, 2019 2:05:43 AM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 54 ms.
Jun 05, 2019 2:05:43 AM org.jpmml.sklearn.Main run
INFO: Converting..
Jun 05, 2019 2:05:43 AM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: The key object (Java class java.lang.Integer) is not a String
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:612)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:60)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:196)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast java.lang.Integer to java.lang.String
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 8 more

Exception in thread "main" java.lang.IllegalArgumentException: The key object (Java class java.lang.Integer) is not a String
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:612)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:60)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:196)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast java.lang.Integer to java.lang.String
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 8 more

**Comment by nedhulseman** [comment]
Also to clarify, I have 6 categorical variables (the ones getting labelBinarized) and 100 word embedding variables names 0,1,2....99. This is the list(range(0, 100)). Is there anything wrong with how I have done the list(range(0,100), None??

**Comment by vruusmann** [comment]
> java.lang.IllegalArgumentException: The key object (Java class java.lang.Integer) is not a String
> at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:60)

You're using Integers as DataFrameMapper keys, but you should be using Strings. Simply wrap your Integer values into  `str(..)` and everything should be fine.

**Comment by nedhulseman** [comment]
Thank you so much!

**Comment by vruusmann** [comment]
It's a "prevailing industry standard" to use String keys everywhere - as `Pipeline` step names, as `DataFrameMapper` transformer names, as `ColumnTransformer` transformer names, and elsewhere.

While JPMML-SkLearn could do this `Integer` -> `String` conversion for you, it intentionally won't, because that would encourage bad behaviour. Next you'd want to use Integers as Pipeline step names, next you'd want to use Double/Boolean for the same, etc.

You should regard DataFrameMapper keys as database column names. No sane database allows you to use Integer column names.
