### ISSUE TITLE
CategoricalDomain datatype change with with_data

### ISSUE THREAD

**Issue by leone281** [jpmml/sklearn2pmml#163]
Hello Villu,
I'm facing a strange issue: I want to convert a date into a a month in the PMML, everything works well as soon as I use with_data = True. The problem is that a prediction with a date that lies in the future may happen and I want the evaluator to continue to work.
So I put with_data = False but the PMML conversion fails.
Example as part of a DataFrameMapper:
``` python
('date', [CategoricalDomain(invalid_value_treatment = 'return_invalid', missing_value_treatment = "as_mode", with_data = **True**), ReplaceTransformer("^[\d\-\/]{5}([\d]{2})[\/-][\d]{2}", "\\1"), LabelEncoder()])
```
<---- this works.

``` python
('date', [CategoricalDomain(invalid_value_treatment = 'return_invalid', missing_value_treatment = "as_mode", with_data = **False**), ReplaceTransformer("^[\d\-\/]{5}([\d]{2})[\/-][\d]{2}", "\\1"), LabelEncoder()])
```
This produce exception when running: sklearn2pmml(pipeline_encoded_pmml, "PATH", with_repr = True)
```
Standard output is empty
Standard error:
Jun 25, 2019 3:00:05 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Jun 25, 2019 3:00:07 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 2151 ms.
Jun 25, 2019 3:00:07 PM org.jpmml.sklearn.Main run
INFO: Converting..
Jun 25, 2019 3:00:07 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException
	at sklearn2pmml.preprocessing.ReplaceTransformer.encodeFeatures(ReplaceTransformer.java:50)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:196)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException
	at sklearn2pmml.preprocessing.ReplaceTransformer.encodeFeatures(ReplaceTransformer.java:50)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:196)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
```
Any clue?
Thanks.
Best Regards,
Riccardo

**Comment by vruusmann** [comment]
The explanation is that `ReplaceTransformer` can only be used with string columns.

If the (sub-)pipeline starts with a `Domain` decorator, then the data type of a column (double, integer, string, boolean etc.) is determined based on its `data_` attribute. This attribute is only present if the `Domain` decorator was initialized with a `with_data = True`.

So, in your second example, the `CategoricalDomain.data_` attribute is missing, and the data type of the "date" column is still double at the time when the `ReplaceTransformer` first sees it.

There appears to be a small omission in the `org.jpmml.sklearn.SkLearnEncoder#updateFeatures(List<Feature>, Transformer)` method that is causing `org.jpmml.converter.WildcardFeature` data type not being updated.

Alternatively, all `Domain` decorator classes should permit the data scientist to specify the intended data type during initialization (eg. using a `dtype` parameter).

**Comment by leone281** [comment]
Hello Villu, thanks for the explanation.
So is there a way to specify the data type?

**Comment by vruusmann** [comment]
@leone281 Upgrade to SkLearn2PMML 0.47.1, and both your code examples will work fine.

**Comment by leone281** [comment]
I confirm it works.
Excellent Villu!
Many thanks.
Riccardo
