### ISSUE TITLE
net.razorvine.pickle.PickleException: expected zero arguments for construction o f ClassDict 

### ISSUE THREAD

**Issue by sin-en-2009** [jpmml/sklearn2pmml#164]
**The following error occurred when I executed the following command**

D:\work> java -jar jpmml-sklearn-executable-1.5-SNAPSHOT.jar --pkl-input
model_2019-07-04.pkl --pmml-output new2.pmml

net.razorvine.pickle.PickleException: expected zero arguments for construction o
f ClassDict (for numpy.ma.core._mareconstruct)
        at net.razorvine.pickle.objects.ClassDictConstructor.construct(ClassDict
Constructor.java:23)
        at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:732)
        at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:200)
        at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:77)
        at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
        at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)
        at org.jpmml.sklearn.Main.run(Main.java:104)
        at org.jpmml.sklearn.Main.main(Main.java:94)
Exception in thread "main" net.razorvine.pickle.PickleException: expected zero a
rguments for construction of ClassDict (for numpy.ma.core._mareconstruct)
        at net.razorvine.pickle.objects.ClassDictConstructor.construct(ClassDict
Constructor.java:23)
        at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:732)
        at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:200)
        at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:77)
        at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
        at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)
        at org.jpmml.sklearn.Main.run(Main.java:104)
        at org.jpmml.sklearn.Main.main(Main.java:94)

**My pipeline assembly process looks like the following**
    mapper = DataFrameMapper(list_tupe)
    from sklearn.model_selection import GridSearchCV
    pipeline = Pipeline([('mapper', mapper), 
                                    ('std', StandardScaler（）),  
                                    ('clf', GridSearchCV(
                                     model_,scoring='roc_auc',cv=2,
                                     n_jobs=12,
                                     param_grid={'C':param_range,'tol':tol_range}
    ))])
**Whether your transformation does not support inline grid search methods？？**

**Comment by vruusmann** [comment]
This unpickling exception means that your `(PMML)Pipeline` object contains an unsupported CPython object (in this case `numpy.ma.core._mareconstruct`).

> Whether your transformation does not support inline grid search methods?

All grid search methods are supported. Simply get rid of all "exotic" CPython objects, and everything will work as advertised.

**Comment by sin-en-2009** [comment]
I see。
I think the error should be in this line of code, because I changed the gridsearch to logical st and then included the following error
fit_coder = OrdinalEncoder(dtype=np.uint32)

java.lang.IllegalArgumentException: numpy.uint32
        at numpy.DType.getDataType(DType.java:69)
        at sklearn.preprocessing.OrdinalEncoder.encodeFeatures(OrdinalEncoder.ja
va:83)
        at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:85)
        at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.jav
a:73)
        at sklearn.Initializer.encodeFeatures(Initializer.java:41)
        at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:85)
        at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:79)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:203)
        at org.jpmml.sklearn.Main.run(Main.java:145)
        at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException: numpy.uint32
        at numpy.DType.getDataType(DType.java:69)

**Comment by vruusmann** [comment]
> fit_coder = OrdinalEncoder(dtype=np.uint32)

Specify a **_signed_** integer type as a temporary workaround.

**Comment by sin-en-2009** [comment]
I still get an error when I change the type  to int.Since the default type of the OrdinalEncoder is np.float64, I specify int.**But if you specify int it doesn't work what type should you use?**

**fit_coder = OrdinalEncoder(dtype=int)**

    def __init__(self, categories='auto', dtype=np.float64):
        self.categories = categories
        self.dtype = dtype

java.lang.IllegalArgumentException: builtins.int
        at numpy.DType.getDataType(DType.java:69)
        at sklearn.preprocessing.OrdinalEncoder.encodeFeatures(OrdinalEncoder.ja
va:83)
        at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:85)
        at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.jav
a:73)
        at sklearn.Initializer.encodeFeatures(Initializer.java:41)
        at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:85)
        at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:79)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:203)
        at org.jpmml.sklearn.Main.run(Main.java:145)
        at org.jpmml.sklearn.Main.main(Main.java:94)

**Comment by vruusmann** [comment]
> But if you specify int it doesn't work what type should you use?

Use `numpy.int` (Numpy data type) instead of `builtins.int` (Python built-in data type).
