### ISSUE TITLE
CategoricalDomain failure

### ISSUE THREAD

**Issue by adishpak** [jpmml/sklearn2pmml#167]
Hi, 
I have this piece of code that runs very day :   

```

    params2 = {'n_estimators': 100,
               'learning_rate': 0.5,
               'seed': 0,
               'subsample': 0.8,
               'n_jobs': 50,
               'colsample_bytree': 0.8,
               'objective': 'binary:logistic',
               'max_depth': 10,
               'min_child_weight': 300,
               'gamma': 2,
               'max_delta_step': 6
               }

    estimator = xgb.XGBClassifier(**params2)
    mapper = DataFrameMapper([(i, None) if j != 'object' and j != 'bool' else (i,
                                                                               [CategoricalDomain(
                                                                                   missing_value_treatment="as_value",
                                                                                   invalid_value_treatment="as_missing",
                                                                                   missing_value_replacement=train_x[
                                                                                       i].value_counts().idxmax(),
                                                                                   invalid_value_replacement=train_x[
                                                                                       i].value_counts().idxmax()),
                                                                                LabelEncoder()])
                              for i, j in
                              zip(train_x.columns.values, train_x.dtypes.values)]
                             , input_df=True, df_out=True)

    rf_pipeline = PMMLPipeline([("mapper", mapper), ("classifier", estimator)])
    rf_pipeline.fit(train_x, train_y)

    sklearn2pmml(rf_pipeline, 'online_viewability.pmml', with_repr=True)

```

it has been running flawlessly for months.
about a week ago it stopped  working with the following error: 
```

java.lang.IllegalArgumentException
	at org.jpmml.converter.InvalidValueDecorator.<init>(InvalidValueDecorator.java:36)
	at sklearn2pmml.decoration.Domain.encodeFeatures(Domain.java:84)
	at sklearn2pmml.decoration.CategoricalDomain.encodeFeatures(CategoricalDomain.java:90)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:85)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:85)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:79)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:199)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException
	at org.jpmml.converter.InvalidValueDecorator.<init>(InvalidValueDecorator.java:36)
	at sklearn2pmml.decoration.Domain.encodeFeatures(Domain.java:84)
	at sklearn2pmml.decoration.CategoricalDomain.encodeFeatures(CategoricalDomain.java:90)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:85)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:85)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:79)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:199)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Traceback (most recent call last):

    sklearn2pmml(rf_pipeline, file_name, with_repr=True)
  File "/usr/lib/python2.7/dist-packages/sklearn2pmml/__init__.py", line 252, in sklearn2pmml
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```
I didn't make any code changes. it suddenly stopped working. 
Do you know what might be the reason ? 

I also reproduced it with the following code and got the same error : 

```
cols = {'var': ['a','b','a','d','h','g','b','a','s','l'], 'prob': [1,1,1,0,0,1,0,1,0,0]}
df = pd.DataFrame(data=cols)

train_x = df.drop(['prob'], axis=1)
train_y = df['prob']
params2 = {'n_estimators': 100,
                  'learning_rate': 0.5,
                  'seed': 0,
                   'subsample': 0.8,
                   'n_jobs': 50,
                   'colsample_bytree': 0.8,
                   'objective': 'binary:logistic',
                   'max_depth': 10,
                  'min_child_weight': 300,
                   'gamma': 2,
                   'max_delta_step': 6}
mapper = DataFrameMapper([(i, None) if j != 'object' and j != 'bool' else (i,
                                                                               [CategoricalDomain(
                                                                                   missing_value_treatment="as_value",
                                                                                   invalid_value_treatment="as_missing",
                                                                                   missing_value_replacement=train_x[
                                                                                       i].value_counts().idxmax(),
                                                                                   invalid_value_replacement=train_x[
                                                                                       i].value_counts().idxmax()),
                                                                                LabelEncoder()])
                              for i, j in
                              zip(train_x.columns.values, train_x.dtypes.values)]
                             , input_df=True, df_out=True)

rf_pipeline = PMMLPipeline([("mapper", mapper), ("classifier", estimator)])
rf_pipeline.fit(train_x, train_y)

sklearn2pmml(rf_pipeline, 'online_viewability.pmml', with_repr=True)

```

Thanks

**Comment by vruusmann** [comment]
You can't specify `invalid_value_treatment="as_missing"` and a non-null invalid value replacement value together.

Invalid values either get converted to missing values, or replaced with a replacement value.

**Comment by adishpak** [comment]
Thanks , 
I changed to : 

```
mapper = DataFrameMapper([(i, None) if j != 'object' and j != 'bool' else (i,
                                                                               [CategoricalDomain(
                                                                                   missing_value_replacement=train_x[
                                                                                       i].value_counts().idxmax(),
                                                                                   invalid_value_replacement=train_x[
                                                                                       i].value_counts().idxmax()),
                                                                                LabelEncoder()])
                              for i, j in
                              zip(train_x.columns.values, train_x.dtypes.values)]
                             , input_df=True, df_out=True)

rf_pipeline = PMMLPipeline([("mapper", mapper), ("classifier", estimator)])
rf_pipeline.fit(train_x, train_y)

sklearn2pmml(rf_pipeline, file_name, with_repr=True)
```

And I'm getting the same error

**Comment by vruusmann** [comment]
The `invalid_value_treatment` attribute defaults to `return_invalid`. You should set it to `as_is` if you want to use an invalid value replacement value.

Sure, the exception message should be a bit more informative here. Reopening this issue to see what can be done about it.

**Comment by adishpak** [comment]
Thanks ! 
Just mentioning that the code did work perfectly until about a week ago.
