### ISSUE TITLE
DeprecationWarning: sklearn.externals.joblib is deprecated

### ISSUE THREAD

**Issue by sam-s** [jpmml/sklearn2pmml#171]
I installed `joblib` using `pip` as indicated in the warning below, but I am still getting it every time.

```
>>> import joblib
>>> joblib.__version__
'0.13.2'
>>> import sklearn
>>> sklearn.__version__
'0.21.2'
>>> import sklearn2pmml
/Users/sam.steingold/.virtualenvs/brazeds/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
>>> sklearn2pmml.__version__
'0.48.0'
```

**Comment by jj1118** [comment]
Actually the `__init__` script still does `from sklearn.externals import joblib` as of now (0.48.0), which leads to an `AttributeError` with scikit-learn 0.21.3:
```
>>> from sklearn2pmml import sklearn2pmml
>>> sklearn2pmml(model, 'test', debug=True)
python: 3.7.3
sklearn: 0.21.3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\sklearn2pmml\__init__.py", line 212, in sklearn2pmml
    print("sklearn.externals.joblib: {0}".format(joblib.__version__))
AttributeError: module 'sklearn.externals.joblib' has no attribute '__version__'
```
