### ISSUE TITLE
Exception for converting joblib model to pmml model

### ISSUE THREAD

**Issue by jiangyurong609** [jpmml/sklearn2pmml#172]
I was trying to convert a joblib model to pmml model, but I got an exception as follows. I read through some issues, it looks like it should have been fixed. I still got the following errors. Please kindly let me know which part I might have missed. For sklearn, my version is 0.21.3, and sklearn2pmml version is latest. 
```java.lang.IllegalArgumentException: The transformer object (Python class column_selector.ColumnSelector) is not a supported Transformer
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:121)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:112)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:612)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at sklearn.pipeline.Pipeline.getOpType(Pipeline.java:50)
	at sklearn.Transformer.updateFeatures(Transformer.java:58)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:83)
	at sklearn.compose.ColumnTransformer.encodeFeatures(ColumnTransformer.java:63)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:85)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:83)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:203)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	13 more

Exception in thread "main" java.lang.IllegalArgumentException: The transformer object (Python class column_selector.ColumnSelector) is not a supported Transformer
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:121)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:112)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:612)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at sklearn.pipeline.Pipeline.getOpType(Pipeline.java:50)
	at sklearn.Transformer.updateFeatures(Transformer.java:58)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:83)
	at sklearn.compose.ColumnTransformer.encodeFeatures(ColumnTransformer.java:63)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:85)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:83)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:203)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 13 more
Traceback (most recent call last):
  File "convertModel.py", line 8, in <module>
```

My ColumnSelector was defined as 
```from sklearn.base import BaseEstimator, TransformerMixin
import numpy as np
class ColumnSelector(BaseEstimator, TransformerMixin):
    #Transformer to select specific fields in the input pandas dataframe and transform to numpy array.
    
    def __init__(self, column):
        self.column = column

    def fit(self, x, y=None):
        return self

    def transform(self, X):
        print(X)
        print(np.array(X[self.column].values))
        return np.array(X[self.column].values)```

**Comment by vruusmann** [comment]
> java.lang.IllegalArgumentException: The transformer object (Python class column_selector.ColumnSelector) is not a supported Transformer

This exception message should be rather clear - the pipeline contains Python class `column_selector.ColumnSelector`, which is not known to/supported by the SkLearn2PMML.

If you need to select columns in your pipeline, then use existing "selectors" such as `sklearn_pandas.DataFrameMapper` or `sklearn.compose.ColumnTransformer` (simply specify mappings from column names/positions to no-op Transformers such as `None` or `"passthrough"`, respectively).

Let's (re-)use existing functionality, rather than reinventing it all.

**Comment by jiangyurong609** [comment]
Thanks so much for the timely response. Sorry, I'm pretty new to those libs. I just want to get the specific column based on column name, therefore, I implemented my own simple selector.  I'm not familiar with DataFrameMapper, would you mind educate me for the possible usage that you mentioned. Your help is highly appreciated. Thank you 

```
    categorical_transformer = PMMLPipeline(steps=[
        ('columnSelector', ColumnSelector('tags')),
        ('multiLabel', CustomMultiLabelBinarizer())
    ])
```

**Comment by vruusmann** [comment]
> I implemented my own simple selector

If you want to convert your simple selector to PMML, then you also need to implement a corresponding SkLearn-to-PMML converter plugin. See https://github.com/jpmml/sklearn2pmml-plugin

> would you mind educate me for the possible usage that you mentioned.

Please see the README files of SkLearn2PMML and JPMML-SkLearn projects:
https://github.com/jpmml/sklearn2pmml#usage
https://github.com/jpmml/jpmml-sklearn#usage

**Comment by vruusmann** [comment]
```
pipeline = PMMLPipeline([
  ("mapper", DataFrameMapper([
    ("tags", CustomMultiLabelBinarizer())
  ]))
])
```

Next, you're going to report that your custom `CustomMultiLabelBinarizer` transformer class is not supported. But I've already given you a pointer what to do about it.
