### ISSUE TITLE
Support for "list maker" syntax in ExpressionTransformer

### ISSUE THREAD

**Issue by leone281** [jpmml/sklearn2pmml#196]
Hello Villu,
I'd like to write a custom transformation of a feature using something like this:
```python
column_tuples = [
    (['feature'], [ContinuousDomain(invalid_value_treatment = 'return_invalid', missing_value_treatment = "as_mode", with_data = True), 
                              Alias(ExpressionTransformer('10-2*X[0]'), name = "expression"),
                              Alias(ExpressionTransformer('max([5, X[0]])'), name = 'margin')])
]
```

It works well at prediction time but when I try to convert it into PMML I get:

```
java.lang.IllegalArgumentException: Python expression \'max([5, X[0]])\' is either invalid or not supported
	at org.jpmml.sklearn.ExpressionTranslator.translate(ExpressionTranslator.java:76)
	at org.jpmml.sklearn.ExpressionTranslator.translate(ExpressionTranslator.java:63)
	at sklearn2pmml.preprocessing.ExpressionTransformer.encodeFeatures(ExpressionTransformer.java:47)
	at sklearn2pmml.decoration.Alias.encodeFeatures(Alias.java:56)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:118)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:118)
	at sklearn.Composite.encodeFeatures(Composite.java:129)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:203)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: org.jpmml.sklearn.ParseException: Encountered unexpected token: "[" "["
    at line 1, column 5.

Was expecting one of:
    "("
    "+"
    "-"
    "False"
    "True"
    "not"
    <FLOAT>
    <INT>
    <NAME>
    <STRING>
```

What am I missing?
Thanks for your help.
Cheers,
Riccardo

**Comment by vruusmann** [comment]
> `ExpressionTransformer('max([5, X[0]])')`

You're using "list maker" syntax `[elem_0, elem_1, .., elem_n]`, which is not supported by the JPMML-SkLearn expression parser component.

This wouldn't be difficult to copy over from the predicate parser component:
https://github.com/jpmml/jpmml-sklearn/blob/1.5.24/src/main/javacc/predicate.jj#L449-L461

Anyway, if this list maker issue were solved, then I can already tell that you would be facing another issue - the parser would throw an java.lang.IllegalArgumentException, which complains that the `max` function is not recognized.

Assuming that you are only dealing with two-element lists, then I'd suggest you to refactor this expression into a simple if-else expression: `ExpressionTransformer('X[0] if X[0] >= 5 else 5')`.

**Comment by leone281** [comment]
Hello Villu,
That helped, thanks!
Do you think it could be possible to write in PMML an explicit model? I mean a model that is a predefined formula?
Thanks again.
Best regards,
Riccardo

**Comment by vruusmann** [comment]
Reopening, because this issue (list maker syntax) isn't implemented yet.
