### ISSUE TITLE
When LightGBM set categorical_feature, sklearn2pmml run error

### ISSUE THREAD

**Issue by SilenceWinter** [jpmml/sklearn2pmml#206]
sklearn2pmml is 0.53.0 , lightgbm is 2.2.3 , python is 3.6.5

Here is my python code ,

``` python 
classifier = LGBMClassifier()
pipeline = PMMLPipeline([ ('classifier', classifier) ])
pipeline.fit(X, y, classifier__categorical_feature=['a'])    # a is the categorical feature name
sklearn2pmml(pipeline, self.pmml_path)  
```
==============================================
the error info as follow:
 05, 2020 5:02:13  org.jpmml.sklearn.Main run
Ϣ: Converting..
 05, 2020 5:02:13  org.jpmml.sklearn.Main run
: Failed to convert
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
**java.lang.IllegalArgumentException: Expected a false (off) categorical split mask for continuous feature a, got true (on)**
	at org.jpmml.lightgbm.Tree.encodeNode(Tree.java:226)
	at org.jpmml.lightgbm.Tree.encodeNode(Tree.java:235)
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
	at org.jpmml.lightgbm.Tree.encodeTreeModel(Tree.java:96)
	at org.jpmml.lightgbm.ObjectiveFunction.createMiningModel(ObjectiveFunction.java:72)
	at org.jpmml.lightgbm.BinomialLogisticRegression.encodeMiningModel(BinomialLogisticRegression.java:47)
	at org.jpmml.lightgbm.GBDT.encodeMiningModel(GBDT.java:394)
	at lightgbm.sklearn.BoosterUtil.encodeModel(BoosterUtil.java:59)
	at lightgbm.sklearn.LGBMClassifier.encodeModel(LGBMClassifier.java:39)
	at lightgbm.sklearn.LGBMClassifier.encodeModel(LGBMClassifier.java:26)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:234)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException: Expected a false (off) categorical split mask for continuous feature a, got true (on)
	at org.jpmml.lightgbm.Tree.encodeNode(Tree.java:226)
	at org.jpmml.lightgbm.Tree.encodeNode(Tree.java:235)
	at org.jpmml.lightgbm.Tree.encodeTreeModel(Tree.java:96)
	at org.jpmml.lightgbm.ObjectiveFunction.createMiningModel(ObjectiveFunction.java:72)
	at org.jpmml.lightgbm.BinomialLogisticRegression.encodeMiningModel(BinomialLogisticRegression.java:47)
	at org.jpmml.lightgbm.GBDT.encodeMiningModel(GBDT.java:394)
	at lightgbm.sklearn.BoosterUtil.encodeModel(BoosterUtil.java:59)
	at lightgbm.sklearn.LGBMClassifier.encodeModel(LGBMClassifier.java:39)
	at lightgbm.sklearn.LGBMClassifier.encodeModel(LGBMClassifier.java:26)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:234)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

**Comment by vruusmann** [comment]
The conversion engine gets operational type information (categorical vs. continuous) from the PMML pipeline. It interprets the contents of the underlying LightGBM text model file according to this information.

Right now  there is a situation where PMML pipeline states that all columns are continuous.

To make things work, you need to indicate at the PMML pipeline level that the column "A" contains categorical features. It can be done by applying the `sklearn2pmml.decoration.CategoricalDomain` decorator class to it.

**Comment by SilenceWinter** [comment]
@vruusmann  Thanks！ I have solved it by your suggestion~

**Comment by vruusmann** [comment]
Expanding my answer a bit more, in case somebody else should come across this issue.

If you train a LightGBM model using the low-level [Training API](https://lightgbm.readthedocs.io/en/latest/Python-API.html#training-api), and then use the JPMML-LightGBM command-line application to convert the LightGBM text model file, then the conversion should succeed. The command-line application gets operational type information from the text model file, which states that column "A" is categorical.

However, if you train LightGBM model using the high-level [Scikit-Learn API](https://lightgbm.readthedocs.io/en/latest/Python-API.html#scikit-learn-api), and then use the SkLearn2PMML package for conversion, then type levels exists on two levels - first at the top-level `PMMLPipeline` object level, and then at the enclosed `LightGBMClassifier` level. If these two bits of information are in conflict with each other, then the `PMMLPipeline` level is given priority/believed to be more correct.

**Comment by cyjj** [comment]
@vruusmann  I just get same error message. But my col `a` is actually a continuous column, that confusing. And I followed instruction of using mapper with decoration here [https://openscoring.io/blog/2019/04/07/converting_sklearn_lightgbm_pipeline_pmml/](url)
