### ISSUE TITLE
xgboost-XGBRegressor element array of zeroes  

### ISSUE THREAD

**Issue by spencerhs5** [jpmml/sklearn2pmml#220]
Having an issue with xgboost pmml export. 

I have an issue on a few datasets but to illustrate I took the audit lgbm audit example from [https://openscoring.io/blog/2019/04/07/converting_sklearn_lightgbm_pipeline_pmml/](url) and made a couple slight modifications.  I simply removed "Income" as a cont_column predictor and made it the y dependent variable. 

```from lightgbm import LGBMClassifier
from sklearn_pandas import DataFrameMapper
from sklearn.preprocessing import LabelBinarizer
from sklearn2pmml import sklearn2pmml
from sklearn2pmml.decoration import CategoricalDomain, ContinuousDomain
from sklearn2pmml.pipeline import PMMLPipeline
import xgboost as xgb

import pandas

df = pandas.read_csv("audit.csv")

cat_columns = ["Education", "Employment", "Marital", "Occupation"]
cont_columns = ["Age", "Hours"]

mapper = DataFrameMapper(
  [([cat_column], [CategoricalDomain(), LabelBinarizer()]) for cat_column in cat_columns] +
  [(cont_columns, ContinuousDomain())]
)
classifier = xgb.XGBRegressor(objective="reg:squarederror") #LGBMClassifier(objective = "binary", n_estimators = 31, random_state = 42)

pipeline = PMMLPipeline([
  ("mapper", mapper),
  ("classifier", classifier)
])
pipeline.fit(df, df["Income"])

sklearn2pmml(pipeline, "LightGBMAudit.pmml") 
```

If I use the lightgbm LGBRegressor(objective="Regression") instead of the xgboost XGBRegressor(objective="reg:squarederror") the export works fine. 

The error I get is:

```FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)
C:\Users\ssadkin\Anaconda3\lib\site-packages\sklearn2pmml\decoration\__init__.py:137: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  X = column_or_1d(X, warn = True)
C:\Users\ssadkin\Anaconda3\lib\site-packages\sklearn2pmml\decoration\__init__.py:137: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  X = column_or_1d(X, warn = True)
C:\Users\ssadkin\Anaconda3\lib\site-packages\sklearn2pmml\decoration\__init__.py:137: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  X = column_or_1d(X, warn = True)
C:\Users\ssadkin\Anaconda3\lib\site-packages\sklearn2pmml\decoration\__init__.py:137: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  X = column_or_1d(X, warn = True)
Standard output is empty
Standard error:
May 19, 2020 5:06:12 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
May 19, 2020 5:06:12 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 33 ms.
May 19, 2020 5:06:12 PM org.jpmml.sklearn.Main run
INFO: Converting..
May 19, 2020 5:06:12 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.RuntimeException: java.io.IOException: Expected 27-element array of zeroes, got [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        at xgboost.sklearn.Booster.loadLearner(Booster.java:54)
        at xgboost.sklearn.Booster.getLearner(Booster.java:42)
        at xgboost.sklearn.BoosterUtil.getLearner(BoosterUtil.java:71)
        at xgboost.sklearn.BoosterUtil.getNumberOfFeatures(BoosterUtil.java:39)
        at xgboost.sklearn.XGBRegressor.getNumberOfFeatures(XGBRegressor.java:35)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:228)
        at org.jpmml.sklearn.Main.run(Main.java:228)
        at org.jpmml.sklearn.Main.main(Main.java:148)
Caused by: java.io.IOException: Expected 27-element array of zeroes, got [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        at org.jpmml.xgboost.XGBoostDataInput.readReserved(XGBoostDataInput.java:179)
        at org.jpmml.xgboost.Learner.load(Learner.java:82)
        at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:95)
        at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:57)
        at xgboost.sklearn.Booster.loadLearner(Booster.java:52)
7 more

Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Expected 27-element array of zeroes, got [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        at xgboost.sklearn.Booster.loadLearner(Booster.java:54)
        at xgboost.sklearn.Booster.getLearner(Booster.java:42)
        at xgboost.sklearn.BoosterUtil.getLearner(BoosterUtil.java:71)
        at xgboost.sklearn.BoosterUtil.getNumberOfFeatures(BoosterUtil.java:39)
        at xgboost.sklearn.XGBRegressor.getNumberOfFeatures(XGBRegressor.java:35)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:228)
        at org.jpmml.sklearn.Main.run(Main.java:228)
        at org.jpmml.sklearn.Main.main(Main.java:148)
Caused by: java.io.IOException: Expected 27-element array of zeroes, got [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        at org.jpmml.xgboost.XGBoostDataInput.readReserved(XGBoostDataInput.java:179)
        at org.jpmml.xgboost.Learner.load(Learner.java:82)
        at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:95)
        at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:57)
        at xgboost.sklearn.Booster.loadLearner(Booster.java:52)
7 more

Traceback (most recent call last):

  File "C:\Users\ssadkin\OD\Projects\BYOM\Insurance Examples\profitability_demo\Audit_Delete.py", line 28, in <module>
    sklearn2pmml(pipeline, "LightGBMAudit.pmml")

  File "C:\Users\ssadkin\Anaconda3\lib\site-packages\sklearn2pmml\__init__.py", line 266, in sklearn2pmml
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

Let me know if I can provide anything else. Thanks in advance!

**Comment by vruusmann** [comment]
What is your XGBoost package version? Is it newer than XGBoost 1.0.0?

In brief, the binary XGBoost model file contains some information in the file area that is supposed to be empty.
