### ISSUE TITLE
Storing model in pmml broken in latest 0.57 release

### ISSUE THREAD

**Issue by MaxNoe** [jpmml/sklearn2pmml#224]
Storing a random forest to pmml does not work anymore with the latest release of sklearn2pmml,
see https://travis-ci.org/github/fact-project/aict-tools/jobs/691364313

```
May 26, 2020 3:39:05 PM org.jpmml.sklearn.Main run

INFO: Parsing PKL..

May 26, 2020 3:39:05 PM org.jpmml.sklearn.Main run

SEVERE: Failed to parse PKL

net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for numpy.dtype)

	at net.razorvine.pickle.objects.ClassDictConstructor.construct(ClassDictConstructor.java:23)

	at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:759)

	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:199)

	at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:81)

	at net.razorvine.pickle.Unpickler.load(Unpickler.java:109)

	at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:102)

	at org.jpmml.sklearn.Main.run(Main.java:161)

	at org.jpmml.sklearn.Main.main(Main.java:151)

Exception in thread "main" net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for numpy.dtype)

	at net.razorvine.pickle.objects.ClassDictConstructor.construct(ClassDictConstructor.java:23)

	at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:759)

	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:199)

	at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:81)

	at net.razorvine.pickle.Unpickler.load(Unpickler.java:109)

	at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:102)

	at org.jpmml.sklearn.Main.run(Main.java:161)

	at org.jpmml.sklearn.Main.main(Main.java:151)

----------------------------- Captured stderr call -----------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/click/testing.py", line 329, in invoke

    cli.main(args=args or (), prog_name=prog_name, **extra)

  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/click/core.py", line 782, in main

    rv = self.invoke(ctx)

  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/click/core.py", line 1066, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke

    return callback(*args, **kwargs)

  File "/home/travis/build/fact-project/aict-tools/aict_tools/scripts/train_energy_regressor.py", line 109, in main

    save_model(

  File "/home/travis/build/fact-project/aict-tools/aict_tools/io.py", line 389, in save_model

    sklearn2pmml(pipeline, model_path)

  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/sklearn2pmml/__init__.py", line 266, in sklearn2pmml

    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

**Comment by vruusmann** [comment]
Most likely a Numpy version issue.
