### ISSUE TITLE
Can't convert xgboost to pmml

### ISSUE THREAD

**Issue by jbibi1296** [jpmml/sklearn2pmml#230]
I am having trouble converting an XGBClassifier to a pmml file.
I tried to put it in a pipeline and convert it but it does not work.
I tested out the pipeline and it predicts properly.
I was originally using xgboost 1.1.0 and it did not work so I rolled back the version to 1.0.0 and it still does not work

Here is my code:

```from sklearn2pmml import sklearn2pmml
print("PMML Pipeline:")
print(chosen_model['Model 2 pmml'][0])
print("")
print("Pipeline Predict Probability:")
print(chosen_model['Model 2 pmml'][0].predict_proba(X)[0][1])
print("")
print("Convert to Pmml:")
sklearn2pmml(chosen_model['Model 2 pmml'][0],'test.pmml')
```

Here is the output:

```PMML Pipeline:
PMMLPipeline(steps=[('classifier_comb_50_2', XGBClassifier(base_score=0.5, booster='gblinear', colsample_bylevel=None,
              colsample_bynode=None, colsample_bytree=None, eta=0.1, gamma=None,
              gpu_id=-1, importance_type='gain', interaction_constraints=None,
              learning_rate=0.01, max_delta_step=None, max_depth=None,
              min_child_weight=None, min_samples_leaf=1, min_samples_split=2,
              missing=nan, monotone_constraints=None, n_estimators=200,
              n_jobs=-1, num_parallel_tree=None, objective='binary:logistic',
              random_state=0, reg_alpha=0, reg_lambda=0, scale_pos_weight=1,
              subsample=None, tree_method=None, validate_parameters=1,
              verbosity=0))])

Pipeline Predict Probability:
0.6403646

Convert to Pmml:
Standard output is empty
Standard error:
Jun 09, 2020 8:37:28 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Jun 09, 2020 8:37:28 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 16 ms.
Jun 09, 2020 8:37:28 PM org.jpmml.sklearn.Main run
INFO: Converting..
Jun 09, 2020 8:37:28 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: gblinear
	at org.jpmml.xgboost.Learner.load(Learner.java:138)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:93)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:57)
	at xgboost.sklearn.Booster.loadLearner(Booster.java:52)
	at xgboost.sklearn.Booster.getLearner(Booster.java:42)
	at xgboost.sklearn.BoosterUtil.getLearner(BoosterUtil.java:71)
	at xgboost.sklearn.BoosterUtil.getNumberOfFeatures(BoosterUtil.java:39)
	at xgboost.sklearn.XGBClassifier.getNumberOfFeatures(XGBClassifier.java:35)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:226)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)

Exception in thread "main" java.lang.IllegalArgumentException: gblinear
	at org.jpmml.xgboost.Learner.load(Learner.java:138)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:93)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:57)
	at xgboost.sklearn.Booster.loadLearner(Booster.java:52)
	at xgboost.sklearn.Booster.getLearner(Booster.java:42)
	at xgboost.sklearn.BoosterUtil.getLearner(BoosterUtil.java:71)
	at xgboost.sklearn.BoosterUtil.getNumberOfFeatures(BoosterUtil.java:39)
	at xgboost.sklearn.XGBClassifier.getNumberOfFeatures(XGBClassifier.java:35)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:226)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-65-a17dacd26595> in <module>
      7 print("")
      8 print("Convert to Pmml:")
----> 9 sklearn2pmml(chosen_model['Model 2 pmml'][0],'test.pmml')

/opt/anaconda3/lib/python3.7/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    264                                 print("Standard error is empty")
    265                 if retcode:
--> 266                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    267         finally:
    268                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

**Comment by jbibi1296** [comment]
I played around with the xgboost parameters and there's only an issue when `booster = 'gblinear'`
