### ISSUE TITLE
Can't convert ConcatTransformer to pmml

### ISSUE THREAD

**Issue by JiyhonLiu** [jpmml/sklearn2pmml#231]
input dataframe is:
```python
df2 = pd.DataFrame({'A': ['a', 'b', 'c'], 'B': ['a', 'c', 'e']})
df2
```

  | A | B
-- | -- | --
0 | a | a
1 | b | c
2 | c | e

the pipeline is:
```python
test_mapper = DataFrameMapper(
    [
        (['A', 'B'], 
         [
             ConcatTransformer('_'), 
             CategoricalDomain(with_data=False, invalid_value_treatment='as_missing'), 
             PMMLLabelEncoder(missing_values=np.NaN)
         ], 
         {'alias': 'combine'},
        ),
    ]
)

test_pipeline = PMMLPipeline([
    ("test_mapper", test_mapper),
])
test_pipeline.fit_transform(df2)
```
output is:
```
array([[0],
       [1],
       [2]])
```

but can not convert the pipeline to pmml
```python
sklearn2pmml.sklearn2pmml(test_pipeline, "test_pipeline.pmml", with_repr=True)
```
```
Standard output is empty
Standard error:
 10, 2020 4:11:32  org.jpmml.sklearn.Main run
INFO: Parsing PKL..
 10, 2020 4:11:32  org.jpmml.sklearn.Main run
INFO: Parsed PKL in 22 ms.
 10, 2020 4:11:32  org.jpmml.sklearn.Main run
INFO: Converting..
 10, 2020 4:11:32  org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: Field concat(A, B) is not decorable
	at sklearn2pmml.decoration.Domain.asWildcardFeature(Domain.java:232)
	at sklearn2pmml.decoration.Domain.encodeFeatures(Domain.java:101)
	at sklearn2pmml.decoration.DiscreteDomain.encodeFeatures(DiscreteDomain.java:72)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:118)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
	at sklearn.Initializer.encodeFeatures(Initializer.java:43)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:118)
	at sklearn.Composite.encodeFeatures(Composite.java:129)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:207)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)

Exception in thread "main" java.lang.IllegalArgumentException: Field concat(A, B) is not decorable
	at sklearn2pmml.decoration.Domain.asWildcardFeature(Domain.java:232)
	at sklearn2pmml.decoration.Domain.encodeFeatures(Domain.java:101)
	at sklearn2pmml.decoration.DiscreteDomain.encodeFeatures(DiscreteDomain.java:72)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:118)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
	at sklearn.Initializer.encodeFeatures(Initializer.java:43)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:118)
	at sklearn.Composite.encodeFeatures(Composite.java:129)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:207)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)
```

**Comment by JiyhonLiu** [comment]
@vruusmann thanks for your kind explanation !!

but if I exchange the position between `ConcatTransformer` and `CategoricalDomain` , still got an Error
```python
test_mapper = DataFrameMapper(
    [
        (['A', 'B'], 
         [
             CategoricalDomain(with_data=False, invalid_value_treatment='as_missing'), 
             ConcatTransformer('_'), 
             PMMLLabelEncoder(missing_values=np.NaN)
         ], 
         {'alias': 'combine'},
        ),
    ]
)

test_pipeline = PMMLPipeline([
    ("test_mapper", test_mapper),
])
test_pipeline.fit_transform(df2)
```

```
ValueError: ['A', 'B']: bad input shape (3, 2)
``` 
so what's the correct steps to combine two string columns and labelencode ?

**Comment by vruusmann** [comment]
The `CategoricalDomain` decorator class operates on a single column. You're trying to pass two columns to it, hence the error.

It's possible to emulate multi-column support using the `sklearn2pmml.decoration.MultiDomain` helper class. In the current case, the mapper definitionm should look something like this:

```python
from sklearn2pmml.decoration import CategoricalDomain, MultiDomain
from sklearn2pmml.preprocessing import ConcatTransformer

mapper = DataFrameMapper([
  (["A", "B"], [MultiDomain(CategoricalDomain(), CategoricalDomain()), ConcatTransformer("_"), LabelEncoder()])
])
```

**Comment by JiyhonLiu** [comment]
Using the `MultiDomain` I can finally call `fit` successful ! 
However converting it to pmml model still failed .
Am I missing something obvious?
BTW.  I wonder whether `ExpressionTransformer` can be transformed to pmml ?
Thanks :) !
```python
test_mapper = DataFrameMapper(
    [
        (['A', 'B'], 
         [
             MultiDomain((CategoricalDomain(with_data=False, invalid_value_treatment='as_missing'), 
                         CategoricalDomain(with_data=False, invalid_value_treatment='as_missing'))),
             ConcatTransformer('_'), 
             PMMLLabelEncoder(missing_values=np.NaN)
         ], 
        ),
    ]
)

test_pipeline = PMMLPipeline([
    ("test_mapper", test_mapper),
])
test_pipeline.fit_transform(df2)

sklearn2pmml.sklearn2pmml(test_pipeline, "test_pipeline.pmml", with_repr=True)
```

```
Standard output is empty
Standard error:
 12, 2020 9:22:20  org.jpmml.sklearn.Main run
INFO: Parsing PKL..
 12, 2020 9:22:20  org.jpmml.sklearn.Main run
INFO: Parsed PKL in 24 ms.
 12, 2020 9:22:20  org.jpmml.sklearn.Main run
INFO: Converting..
 12, 2020 9:22:20  org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: Attribute 'sklearn2pmml.decoration.MultiDomain.domains' has an unsupported value (Java class [Ljava.lang.Object;)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:45)
	at org.jpmml.python.PyClassDict.get(PyClassDict.java:82)
	at org.jpmml.python.PyClassDict.getList(PyClassDict.java:257)
	at org.jpmml.python.PyClassDict.getList(PyClassDict.java:261)
	at sklearn2pmml.decoration.MultiDomain.getDomains(MultiDomain.java:61)
	at sklearn2pmml.decoration.MultiDomain.encodeFeatures(MultiDomain.java:38)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:118)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
	at sklearn.Initializer.encodeFeatures(Initializer.java:43)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:118)
	at sklearn.Composite.encodeFeatures(Composite.java:129)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:207)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)
Caused by: java.lang.ClassCastException: Cannot cast [Ljava.lang.Object; to java.util.List
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:43)
	... 13 more

Exception in thread "main" java.lang.IllegalArgumentException: Attribute 'sklearn2pmml.decoration.MultiDomain.domains' has an unsupported value (Java class [Ljava.lang.Object;)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:45)
	at org.jpmml.python.PyClassDict.get(PyClassDict.java:82)
	at org.jpmml.python.PyClassDict.getList(PyClassDict.java:257)
	at org.jpmml.python.PyClassDict.getList(PyClassDict.java:261)
	at sklearn2pmml.decoration.MultiDomain.getDomains(MultiDomain.java:61)
	at sklearn2pmml.decoration.MultiDomain.encodeFeatures(MultiDomain.java:38)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:118)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
	at sklearn.Initializer.encodeFeatures(Initializer.java:43)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:118)
	at sklearn.Composite.encodeFeatures(Composite.java:129)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:207)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)
Caused by: java.lang.ClassCastException: Cannot cast [Ljava.lang.Object; to java.util.List
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:43)
	... 13 more
```

**Comment by vruusmann** [comment]
@JiyhonLiu Check your python code - the `MultiDomain.domains` attribute must be a list of decorators, but you're supplying a two-element tuple right now!

Unsure if/how the `fit(X, y)` method can succeed right now. However, if your change this attribute to a list, then both training and conversion to PMML should be okay.

**Comment by vruusmann** [comment]
OK, my bad - the earlier code example was incomplete/incorrect.

Was:
```python
MultiDomain(CategoricalDomain(), CategoricalDomain())
```

Intended/should have been:
```python
MultiDomain([CategoricalDomain(), CategoricalDomain()])
```
