### ISSUE TITLE
mapper.fit_transform(X_train, y_train) works but PMML conversion failed

### ISSUE THREAD

**Issue by TGanor** [jpmml/sklearn2pmml#247]
Hi Villu,

I'm trying to create a pmml file from the sklearn model and get the following **error:** 

```
Standard output is empty
Standard error:
Oct 07, 2020 1:24:51 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Oct 07, 2020 1:24:51 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 59 ms.
Oct 07, 2020 1:24:51 PM org.jpmml.sklearn.Main run
INFO: Converting..
Oct 07, 2020 1:24:51 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: Attribute 'sklearn2pmml.preprocessing.ReplaceTransformer.replacement' has an unsupported value (Java class net.razorvine.pickle.objects.ClassDictConstructor)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:45)
	at org.jpmml.python.PythonObject.get(PythonObject.java:83)
	at org.jpmml.python.PythonObject.getString(PythonObject.java:143)
	at sklearn2pmml.preprocessing.ReplaceTransformer.getReplacement(ReplaceTransformer.java:64)
	at sklearn2pmml.preprocessing.ReplaceTransformer.encodeFeatures(ReplaceTransformer.java:44)
	at sklearn.Transformer.encode(Transformer.java:60)
	at sklearn.compose.ColumnTransformer.encodeFeatures(ColumnTransformer.java:63)
	at sklearn.Transformer.encode(Transformer.java:60)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
	at sklearn.Initializer.encodeFeatures(Initializer.java:43)
	at sklearn.Transformer.encode(Transformer.java:60)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:215)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDictConstructor to java.lang.String
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:43)
	... 14 more

Exception in thread "main" java.lang.IllegalArgumentException: Attribute 'sklearn2pmml.preprocessing.ReplaceTransformer.replacement' has an unsupported value (Java class net.razorvine.pickle.objects.ClassDictConstructor)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:45)
	at org.jpmml.python.PythonObject.get(PythonObject.java:83)
	at org.jpmml.python.PythonObject.getString(PythonObject.java:143)
	at sklearn2pmml.preprocessing.ReplaceTransformer.getReplacement(ReplaceTransformer.java:64)
	at sklearn2pmml.preprocessing.ReplaceTransformer.encodeFeatures(ReplaceTransformer.java:44)
	at sklearn.Transformer.encode(Transformer.java:60)
	at sklearn.compose.ColumnTransformer.encodeFeatures(ColumnTransformer.java:63)
	at sklearn.Transformer.encode(Transformer.java:60)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
	at sklearn.Initializer.encodeFeatures(Initializer.java:43)
	at sklearn.Transformer.encode(Transformer.java:60)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:215)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDictConstructor to java.lang.String
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:43)
	... 14 more

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-67-ff0c1f36a757> in <module>
      5 
      6 out_file = "tesoct_7.pmml"
----> 7 generate_pmml(pipeline, out_file)

~/SageMaker/Tamir/PMML/inter_pipes.py in generate_pmml(pipeline, file_path, output)
    264     shot
    265     """
--> 266     sklearn2pmml(pipeline, file_path)
    267     if output:
    268         print(open(file_path).read())

~/.local/lib/python3.6/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    256                                 print("Standard error is empty")
    257                 if retcode:
--> 258                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    259         finally:
    260                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams


```
I am using the following **code:**:

```
recorder.features = []
recorder.out_df=True
def my_to_lower(g):
    return g.group(0).lower()
def create_col_missmatch(mapper: DataFrameMapper, city1:str, city2:str , new_field:str):
    feature = (
    [city1,city2],
    [               ColumnTransformer([
                        ('city1',CastTransformer(str), [0]),
                        ('city2',CastTransformer(str), [1]),
                         ]),
                    ColumnTransformer([
                        ('city1', ReplaceTransformer('[A-Z]+',my_to_lower), [0]),
                        ('city2',  ReplaceTransformer('[A-Z]+',my_to_lower), [1]),
                    ])
                    ,ExpressionTransformer(f"1 if (X[0] != X[1])  else 0") #removed: , dtype = float
                    ,Alias(CastTransformer(int), name=new_field)
            ]
                ,{'alias': new_field})
    mapper.features = `mapper.features` + [feature]
    return mapper.features

create_col_missmatch(recorder,'accountcity','actimizeenrichmentconnectioncity','city_missmatch')
```
and i **get** :
```
`[(['accountcity', 'actimizeenrichmentconnectioncity'],
  [ColumnTransformer(transformers=[('city1', CastTransformer(dtype=<class 'str'>),
                                    [0]),
                                   ('city2', CastTransformer(dtype=<class 'str'>),
                                    [1])]),
   ColumnTransformer(transformers=[('city1',
                                    ReplaceTransformer(pattern='[A-Z]+',
                                                       replacement=<function my_to_lower at 0x7f8faf222d08>),
                                    [0]),
                                   ('city2',
                                    ReplaceTransformer(pattern='[A-Z]+',
                                                       replacement=<function my_to_lower at 0x7f8faf222d08>),
                                    [1])]),
   ExpressionTransformer(expr='1 if (X[0] != X[1])  else 0'),
   Alias(name='city_missmatch', transformer=CastTransformer(dtype=<class 'int'>))],
  {'alias': 'city_missmatch'})]`
```

```
pipeline = PMMLPipeline([
	("recorder", recorder),
    ("classifier",xgb.XGBClassifier())])

recorder.df_out=True
df = recorder.fit_transform(X_train, y_train)
all looks fine and 

pipeline.fit(X_train, y_train)
pipeline.verify(X_train.head(20))
pipeline.verification.precision = 1e-6
pipeline.verification.zeroThreshold = 1e-6

out_file = "tesoct_7.pmml"
generate_pmml(pipeline, out_file)
```

i am getting the error above

Could you please tell me what's wrong with my code? 
_The fit_transfer works but the conversion to PMML fail_

Thanks Tamir

**Comment by vruusmann** [comment]
> Could you please tell me what's wrong with my code?

The value of the `sklearn2pmml.preprocessing.ReplaceTransformer.replacement` attribute must be string, but you're supplying a function (function reference) instead.

I wonder if it's even possible to pickle function references? The pickle file contains an instruction "invoke function 'my_to_lower(g)'", but the actual **function body** is not stored. As such, it's impossible for the SkLearn2PMML/JPMML-SkLearn software stack to do anything useful.

> The fit_transfer works but the conversion to PMML fail

The running Python script has `my_to_lower(g)` function body available.

However, if you save your pipeline to a pickle file, and then load it back into a new/plain-vanilla Python session, then the `pipeline.predict(X)` would also fail.

The simplest solution is to make the `my_to_lower(g)` function return a Python string.

Before - function is not pickleable:
```python
def my_to_lower(g):
    return g.group(0).lower()

ColumnTransformer([
	('city1', ReplaceTransformer('[A-Z]+',my_to_lower), [0]),
	('city2',  ReplaceTransformer('[A-Z]+',my_to_lower), [1]),
])
```

After - function returns a string that is pickleable:
```python
def my_to_lower():
    return "(0)"

ColumnTransformer([
	('city1', ReplaceTransformer('[A-Z]+',my_to_lower()), [0]),
	('city2',  ReplaceTransformer('[A-Z]+',my_to_lower()), [1]),
])
```

I don't remember exactly if `ReplaceTransformer` supports regex groups (ie. `(0)`) or not. Maybe it depends on the RegEx backend (PCRE vs non-PCRE)

However, please note that if you need to standardize `ReplaceTransformer` transformation results further (eg. conversion to lowercase), then you should be using the `sklearn2pmml.preprocessing.StringNormalizer` for that:
```python
ColumnTransformer([
	('city1', [ReplaceTransformer('[A-Z]+',my_to_lower()), StringNormalizer(function = "lowercase")], [0]),
])
```

**Comment by TGanor** [comment]
Thanks for the great support it is working now
