### ISSUE TITLE
Error in creating PMML file when using SimpleImputer

### ISSUE THREAD

**Issue by MC55652** [jpmml/sklearn2pmml#249]
Hi Villu,

I'm trying to train a pipeline and convert it to PMML. 
my pipeline contains a mapper and an XGBoost clasifier. 
In my mapper, I'm creating new features based on date features.
The new features are: IsWeekend and weekday 

When running the mapper it works, but when trying to convert to PMML, I'm getting this error:

    Standard output is empty
	Standard error:
	Oct 08, 2020 7:56:18 AM org.jpmml.sklearn.Main run
	INFO: Parsing PKL..
	Oct 08, 2020 7:56:18 AM org.jpmml.sklearn.Main run
	INFO: Parsed PKL in 146 ms.
	Oct 08, 2020 7:56:18 AM org.jpmml.sklearn.Main run
	INFO: Converting..
	Oct 08, 2020 7:56:18 AM org.jpmml.sklearn.Main run
	SEVERE: Failed to convert
	java.lang.IllegalArgumentException: Field imputer(string(partyphoneupdatedate)) is already defined. Please refactor the pipeline so that it would not contain duplicate field declarations, or use the sklearn2pmml.decoration.Alias wrapper class to override the default name with a custom name (eg. Alias(transformer = ..., name = ...))
		at org.jpmml.sklearn.SkLearnEncoder.addDerivedField(SkLearnEncoder.java:71)
		at org.jpmml.converter.PMMLEncoder.createDerivedField(PMMLEncoder.java:157)
		at sklearn.impute.ImputerUtil.encodeFeature(ImputerUtil.java:78)
		at sklearn.impute.SimpleImputer.encodeFeatures(SimpleImputer.java:74)
		at sklearn.Transformer.encode(Transformer.java:60)
		at sklearn.Composite.encodeFeatures(Composite.java:119)
		at sklearn.pipeline.PipelineTransformer.encodeFeatures(PipelineTransformer.java:66)
		at sklearn.Transformer.encode(Transformer.java:60)
		at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
		at sklearn.Initializer.encodeFeatures(Initializer.java:43)
		at sklearn.Transformer.encode(Transformer.java:60)
		at sklearn.Composite.encodeFeatures(Composite.java:119)
		at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:215)
		at org.jpmml.sklearn.Main.run(Main.java:233)
		at org.jpmml.sklearn.Main.main(Main.java:151)
	Caused by: java.lang.IllegalArgumentException: Field imputer(string(partyphoneupdatedate)) is already defined
		at org.jpmml.converter.PMMLEncoder.checkName(PMMLEncoder.java:291)
		at org.jpmml.converter.PMMLEncoder.addDerivedField(PMMLEncoder.java:149)
		at org.jpmml.sklearn.SkLearnEncoder.addDerivedField(SkLearnEncoder.java:63)
		... 14 more

	Exception in thread "main" java.lang.IllegalArgumentException: Field imputer(string(partyphoneupdatedate)) is already defined. Please refactor the pipeline so that it would not contain duplicate field declarations, or use the sklearn2pmml.decoration.Alias wrapper class to override the default name with a custom name (eg. Alias(transformer = ..., name = ...))
		at org.jpmml.sklearn.SkLearnEncoder.addDerivedField(SkLearnEncoder.java:71)
		at org.jpmml.converter.PMMLEncoder.createDerivedField(PMMLEncoder.java:157)
		at sklearn.impute.ImputerUtil.encodeFeature(ImputerUtil.java:78)
		at sklearn.impute.SimpleImputer.encodeFeatures(SimpleImputer.java:74)
		at sklearn.Transformer.encode(Transformer.java:60)
		at sklearn.Composite.encodeFeatures(Composite.java:119)
		at sklearn.pipeline.PipelineTransformer.encodeFeatures(PipelineTransformer.java:66)
		at sklearn.Transformer.encode(Transformer.java:60)
		at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
		at sklearn.Initializer.encodeFeatures(Initializer.java:43)
		at sklearn.Transformer.encode(Transformer.java:60)
		at sklearn.Composite.encodeFeatures(Composite.java:119)
		at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:215)
		at org.jpmml.sklearn.Main.run(Main.java:233)
		at org.jpmml.sklearn.Main.main(Main.java:151)
	Caused by: java.lang.IllegalArgumentException: Field imputer(string(partyphoneupdatedate)) is already defined
		at org.jpmml.converter.PMMLEncoder.checkName(PMMLEncoder.java:291)
		at org.jpmml.converter.PMMLEncoder.addDerivedField(PMMLEncoder.java:149)
		at org.jpmml.sklearn.SkLearnEncoder.addDerivedField(SkLearnEncoder.java:63)
		... 14 more

This is my functions:

	def addDatetimeFeatues(mapper: DataFrameMapper, dateColumn: str):
	"""
	Accepts the datetime column and create a datetime based feature out of it
	"""
	weekday(mapper,dateColumn,f'{dateColumn}_weekDay')
	IsWeekend(mapper,dateColumn,f'{dateColumn}_isWeekend')

	counter = 0

	def weekday(mapper: DataFrameMapper, date: str, alias: str):
	"""
	Map dates to days of the week. Monday = 1 etc.
	Will return -1 for null or empty inputs
	"""
	feature = (
	[date],
	[
	as_date(),
	DaysSinceYearTransformer(1970), # Thursday
	ExpressionTransformer(
	"-999.01 if X[0] == -25567 else (X[0] + 3 ) % 7"
	),
	Alias(CastTransformer(float), name=alias)
	],
	{'alias': alias}
	)
	mapper.features = mapper.features + [feature]

	def IsWeekend(mapper: DataFrameMapper, date: str, alias: str):
	'''
	Determines if a date falls on a weekend.

	'''
	feature = (
	    [date],
	    [
	        as_date(),
	        DaysSinceYearTransformer(1970),
	        ExpressionTransformer(
	            "1 if ( (X[0] + 3 ) % 7 == 6 or (X[0] + 3 ) % 7 == 5 ) else 0 "
	        ),
	        Alias(CastTransformer(float), name=alias)
	    ],
	    {'alias': alias}
	)
	mapper.features = mapper.features + [feature]

	def as_date(replace_date: str = '01/01/1900 00:00:00:000', alias="rplc_date"):
	global counter

	replTrans = Alias(ReplaceTransformer(
	    "(\d{1,2})/(\d{1,2})/(\d{2,4}) (.*?)(:\d\d\d)$",
	    "\\3-\\2-\\1T\\4"
	), name=alias + str(counter))
	imputer2 = SimpleImputer(
	    missing_values='NaT', strategy='constant', fill_value=replace_date
	)

	imputer1 = SimpleImputer(
	    missing_values=np.nan, strategy='constant', fill_value=replace_date
	)
	counter += 1
	return make_pipeline(
	    CastTransformer(str), imputer1, imputer2,  replTrans, CastTransformer("datetime64[s]")
	    
	)

This is the code for the pipeline:

     recorder= DataFrameMapper([])
	 recorder.features = []

	for date in dates_with_time:
	    addDatetimeFeatues(recorder, date)

	pipeline = PMMLPipeline([
	    ("mapper", recorder)
	    ,("select", ColumnTransformer([("drop", "drop", cat_cols)], remainder='passthrough'))
	    ,("classifier", XGBClassifier())
	])

    pipeline.fit(crude_df.reset_index(),y_train)
    out_file = "pmml_model.pmml"
    generate_pmml(pipeline, out_file)

I appreciate your help,
Michal

**Comment by vruusmann** [comment]
> In my mapper, I'm creating new features based on date features.
> The new features are: IsWeekend and weekday

In your code you're applying the same transformation to the same column multiple times (each time in a different location).

The PMML converter is constructing `DerivedField` element names using the formula `transformation(column)` (here: `string(partyphoneupdatedate)`). This naive field naming approach fails in the above scenario - the PMML document must not contain duplicate field names.

There are two solutions possible:

1. Refactor your data flow that a transformation is applied to a column not more than once.
2. Override the default `DerivedField` element name with a custom name. 

In the ideal world you could do both - first refactor the data flow, and then specify short and meaningful field names yourself.

**Comment by vruusmann** [comment]
Refactoring the data flow.

Right now your DataFrameMapper "chooses" the same column multiple times; in each time, the sub-pipeline starts with the same step (imputation of missing values):
```python
mapper = DataFrameMapper([
  ("mycolumn", [SimpleImputer(), FirstTransformation()])
  ("mycolumn", [SimpleImputer(), SecondTransformation()])
])
```

During the refactoring, keep the common steps in the "root flow", and branch uncommon steps into two child data flow branches using the `sklearn.pipeline.FeatureUnion` branching meta-transformation:
```python
mapper = DataFrameMapper([
  ("mycolumn", [SimpleImputer(), FeatureUnion([
    ("first", FirstTransformer()),
    ("second", SecondTransformer())
  ])])
])
```

**Comment by vruusmann** [comment]
It's possible to soft-rename fields using the `sklearn2pmml.decoration.Alias` decorator. I can see that your code already makes extensive use of this functionality.

Have you tried applying the `Alias` decorator to your `SimpleImputer` steps? Perhaps you can solve the field naming conflict by renaming the second imputer instance from `imputer(string(partyphoneupdatedate))` to `duplicate_imputer(string(partyphoneupdatedate))`?

If soft-renaming does not work, then you may try hard-renaming by specifying the `pmml_name_` attribute manually. See https://github.com/jpmml/jpmml-sklearn/#141 for a detailed rationale, discussion and implementation.

Something like this should do:
```
first_imputer = SimpleImputer()
first_imputer.pmml_name_ = "first_imputer(mycolumn)"
second_imputer = SimpleImputer()
second_imputer.pmml_name_ = "second_imputer(mycolumn)"

mapper = DataFrameMapper([
  ("mycolumn", [first_imputer, FirstTransformation()])
  ("mycolumn", [second_imputer, SecondTransformation()])
])
```

If the Scikit-Learn framwork complains about the non-standard `pmml_name_` attribute during model training (ie. when invoking the `(PMML)Pipeline.fit(X, y)` method), then you may also set those attributes after the training.
