### ISSUE TITLE
Failed to convert,the adaboost (customMLP as base_estimator) convert to pmml,how to solve this question?

### ISSUE THREAD

**Issue by zk122** [jpmml/sklearn2pmml#253]
Standard output is empty
Standard error:
ʮ 19, 2020 2:50:47  org.jpmml.sklearn.Main run
Ϣ: Parsing PKL..
ʮ 19, 2020 2:50:50  org.jpmml.sklearn.Main run
Ϣ: Parsed PKL in 2564 ms.
ʮ 19, 2020 2:50:50  org.jpmml.sklearn.Main run
Ϣ: Converting..
ʮ 19, 2020 2:50:50  org.jpmml.sklearn.Main run
: Failed to convert
java.lang.IllegalArgumentException: The transformer object (Python class sklearn.ensemble._weight_boosting.AdaBoostClassifier) is not a supported Transformer
	at org.jpmml.python.CastFunction.apply(CastFunction.java:45)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:103)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:94)
	at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:638)
	at sklearn.TransformerUtil.getHead(TransformerUtil.java:36)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:194)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.lang.Class.cast(Unknown Source)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:43)
	... 7 more

Exception in thread "main" java.lang.IllegalArgumentException: The transformer object (Python class sklearn.ensemble._weight_boosting.AdaBoostClassifier) is not a supported Transformer
	at org.jpmml.python.CastFunction.apply(CastFunction.java:45)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:103)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:94)
	at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:638)
	at sklearn.TransformerUtil.getHead(TransformerUtil.java:36)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:194)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.lang.Class.cast(Unknown Source)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:43)
	... 7 more

Traceback (most recent call last):
  File "E:/liushuangjiang/zhouke/adaboost/adaboost.py", line 60, in <module>
    sklearn2pmml(pipeline, "./pmml/adaboost4.pmml", with_repr = True)
  File "C:\Users\liushuangjiang\Anaconda3\envs\tf\lib\site-packages\sklearn2pmml\__init__.py", line 266, in sklearn2pmml
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams

**Comment by vruusmann** [comment]
> The transformer object (Python class sklearn.ensemble._weight_boosting.AdaBoostClassifier) is not a supported Transformer

See the above exception message - class `sklearn.ensemble.AdaBoostClassifier` is not supported.

If I recall correctly, then `AdaBoostClassifier` was computing probabilities using a separate/expensive function, which would be too much work to translate to PMML.

Consider switching to some alternative boosting algorithm/ML framework.

**Comment by zk122** [comment]
ok,which boosting algrithom will being better ? two classifies and have to deploy on android
