### ISSUE TITLE
Failed to convert PKL to PMML

### ISSUE THREAD

**Issue by chenwenjun1995** [jpmml/sklearn2pmml#268]
this is my code

```python
from __future__ import print_function
import matplotlib
import seaborn
import matplotlib.pyplot as plot
import joblib

housing = pd.read_csv('kc_train.csv')
target=pd.read_csv('kc_train2.csv')

from sklearn.model_selection import train_test_split
housing_train,housing_test,target_train,target_test = train_test_split(housing,target,test_size=0.2)

from sklearn.preprocessing import MinMaxScaler
minmax_scaler=MinMaxScaler()
minmax_scaler.fit(housing_train)
scaler_housing=minmax_scaler.transform(housing_train)
scaler_housing=pd.DataFrame(scaler_housing,columns=housing_train.columns)
#scaler_housing.info()
#print(scaler_housing)

mm=MinMaxScaler()
mm.fit(housing_test)
scaler_t=mm.transform(housing_test)
scaler_t=pd.DataFrame(scaler_t,columns=housing_test.columns)

from sklearn2pmml import PMMLPipeline
LR_reg = PMMLPipeline([("regression", LinearRegression())])
LR_reg.fit(scaler_housing,target_train)
```

above code is ok

but when I run this code 

```python
from sklearn2pmml import sklearn2pmml  
sklearn2pmml(LR_reg, "house_predict.pmml", with_repr=True)
```

I get this error
```
Standard output is empty
Standard error:
Feb 25, 2021 5:07:38 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Feb 25, 2021 5:07:38 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 15 ms.
Feb 25, 2021 5:07:38 PM org.jpmml.sklearn.Main run
INFO: Converting PKL to PMML..
Feb 25, 2021 5:07:38 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert PKL to PMML
java.lang.IllegalArgumentException: Expected 1-dimensional array, got 2-dimensional ([1, 13]) array
	at org.jpmml.python.PythonObject.getArrayShape(PythonObject.java:253)
	at sklearn.linear_model.LinearRegressor.getCoefShape(LinearRegressor.java:55)
	at sklearn.linear_model.LinearRegressor.getNumberOfFeatures(LinearRegressor.java:37)
	at sklearn.StepUtil.checkNumberOfFeatures(StepUtil.java:36)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:229)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)

Exception in thread "main" java.lang.IllegalArgumentException: Expected 1-dimensional array, got 2-dimensional ([1, 13]) array
	at org.jpmml.python.PythonObject.getArrayShape(PythonObject.java:253)
	at sklearn.linear_model.LinearRegressor.getCoefShape(LinearRegressor.java:55)
	at sklearn.linear_model.LinearRegressor.getNumberOfFeatures(LinearRegressor.java:37)
	at sklearn.StepUtil.checkNumberOfFeatures(StepUtil.java:36)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:229)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-121-72e793ebaa69> in <module>
      5 from sklearn2pmml import sklearn2pmml
----> 6 sklearn2pmml(LR_reg, "house_predict.pmml", with_repr=True)
      7 #joblib.dump(LR_reg, './model.pkl')

/opt/conda/lib/python3.6/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    256                                 print("Standard error is empty")
    257                 if retcode:
--> 258                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    259         finally:
    260                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

can you give me some advice

**Comment by vruusmann** [comment]
@chenwenjun1995 Please stop editing your question - you're only making the formatting worse!

**Comment by chenwenjun1995** [comment]
> @chenwenjun1995 Please stop editing your question - you're only making the formatting worse!

Sorry, It's ok now

**Comment by vruusmann** [comment]
See the description of the `[LinearRegression.coef_](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html)` attribute:

> Estimated coefficients for the linear regression problem. .. while if only one target is passed, this is a 1D array of length n_features.

PMML deals with single-target models. Hence, the value of the `coef_` attribute should be a 1D array.

You have a 2D array there, hence the converter is confused.

For starters you should re-organize your pipeline and do feature engineering inside the pipeline as well:
```python
pipeline = PMMLPipeline([
  ("scaler", MinMaxScaler()),
  ("regression", LinearRegression())
])
pipeline.fit(housing_train, target_train)
```

It's functionally identical to your code, but is much-much simpler to read and execute.

I also believe that it will resolve the array dimensionality problem. Can you run this experiment, and report back the results?
