### ISSUE TITLE
Working sklearn model fails `sklearn2pmml` with `java.lang.NullPointerException`

### ISSUE THREAD

**Issue by MattShirley** [jpmml/sklearn2pmml#284]
This is a minimal reproducible model that results in error. The classifiers used are ColumnTransformer, StandardScaler, OneHotEncoder, LinearSVR. All of these are listed as supported by `sklearn2pmml`.

I've run examples fine and removing the categorical variables also works. The only think I can think of is that I have categorical columns that are always 0/false. This is true in my minimal example below, as well as the training data, which includes shipping data and some hours outside operation currently never have data populated. Is this use case supported?

Thank you in advance for any possible direction on this issue. I love this project, which is helping me avoid pickling sklearn classifiers in production.

```
/usr/local/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/usr/local/lib/python3.9/subprocess.py:937: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/usr/local/lib/python3.9/subprocess.py:942: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
Standard output is empty
Standard error:
May 24, 2021 11:23:15 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
May 24, 2021 11:23:15 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 35 ms.
May 24, 2021 11:23:15 PM org.jpmml.sklearn.Main run
INFO: Converting PKL to PMML..
May 24, 2021 11:23:15 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert PKL to PMML
java.lang.NullPointerException
	at org.jpmml.converter.ValueUtil.asInt(ValueUtil.java:91)
	at org.jpmml.converter.ValueUtil.asInteger(ValueUtil.java:102)
	at org.jpmml.converter.ValueUtil.lambda$asIntegers$1(ValueUtil.java:112)
	at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:638)
	at sklearn.preprocessing.MultiOneHotEncoder.encodeFeatures(MultiOneHotEncoder.java:132)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.compose.ColumnTransformer.encodeFeatures(ColumnTransformer.java:63)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:212)
	at org.jpmml.sklearn.Main.run(Main.java:244)
	at org.jpmml.sklearn.Main.main(Main.java:161)

Exception in thread "main" java.lang.NullPointerException
	at org.jpmml.converter.ValueUtil.asInt(ValueUtil.java:91)
	at org.jpmml.converter.ValueUtil.asInteger(ValueUtil.java:102)
	at org.jpmml.converter.ValueUtil.lambda$asIntegers$1(ValueUtil.java:112)
	at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:638)
	at sklearn.preprocessing.MultiOneHotEncoder.encodeFeatures(MultiOneHotEncoder.java:132)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.compose.ColumnTransformer.encodeFeatures(ColumnTransformer.java:63)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:212)
	at org.jpmml.sklearn.Main.run(Main.java:244)
	at org.jpmml.sklearn.Main.main(Main.java:161)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-6a8dfc5565e4> in <module>
    107
    108 filename = "model.tmp"
--> 109 sklearn2pmml(model, filename)

~/.local/lib/python3.9/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    256                                 print("Standard error is empty")
    257                 if retcode:
--> 258                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    259         finally:
    260                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

Code:

```python
import pandas as pd

from sklearn2pmml import make_pmml_pipeline, sklearn2pmml
from sklearn2pmml.pipeline import PMMLPipeline

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.svm import LinearSVR

data = {'distance_to_ndc': {0: 2.5858304911528864, 1: 2.5858304911528864},
 'ndc': {0: 'NDC DALLAS TX', 1: 'NDC DALLAS TX'},
 'day_of_week': {0: 4, 1: 5},
 'hour_of_day': {0: 6, 1: 6},
 'density': {0: 3897.622193, 1: 3897.622193},
 'is_military': {0: 0, 1: 0},
 'is_not_continental_us': {0: 0, 1: 0},
 'AK': {0: 0, 1: 0},
 'HI': {0: 0, 1: 0},
 'PR': {0: 0, 1: 0},
 'VI': {0: 0, 1: 0},
 'AE': {0: 0, 1: 0},
 'AP': {0: 0, 1: 0},
 'GU': {0: 0, 1: 0},
 'time_hours': {0: 48.0, 1: 45.0}}

df = pd.DataFrame(data)

X_train = df.drop(["time_hours"], axis=1)
y_train = df[["time_hours"]]

numeric_features = ["distance_to_ndc", "density"]
numeric_transformer = StandardScaler()

categorical_features = [
    "ndc",
    "day_of_week",
    "hour_of_day",
    "is_military",
    "is_not_continental_us",
    "AK",
    "HI",
    "PR",
    "VI",
    "AE",
    "AP",
    "GU",
]

categorical_transformer = OneHotEncoder(
    drop="if_binary",
    categories=[
        ['NDC NEW JERSEY NJ',
        'NDC JAXVILLE FL',
        'SCF SAN JUAN PR',
        'NDC SPFLD MA',
        'NDC PHILA PA',
        'NDC PITTSBURGH PA',
        'NDC WASHINGTON DC',
        'NDC GREENSBORO NC',
        'NDC CINCINN OH',
        'NDC ATLANTA GA',
        'NDC MEMPHIS TN',
        'NDC ST LOUIS MO',
        'NDC DETROIT MI',
        'NDC CHICAGO IL',
        'NDC MPLS/STP MN',
        'NDC DES MOINES IA',
        'NDC DENVER CO',
        'NDC KANS CITY KS',
        'NDC DALLAS TX',
        'NDC SEATTLE WA',
        'NDC LOS ANGELS CA',
        'NDC SAN FRAN CA'],  # ndc
        list(range(7)),  # day of week
        list(range(24)),  # hour of day
        [0, 1],  # is_military
        [0, 1],  # is_not_continental_us
        [0, 1],  # AK
        [0, 1],  # HI
        [0, 1],  # PR
        [0, 1],  # VI
        [0, 1],  # AE
        [0, 1],  # AP
        [0, 1],  # GU
    ],
)

preprocessor = ColumnTransformer(
    transformers=[
        ("numerical", numeric_transformer, numeric_features),
        ("categorical", categorical_transformer, categorical_features),
    ]
)

clf = LinearSVR(C=1)

# Append classifier to preprocessing pipeline.
# Now we have a full prediction pipeline.
steps=[
    ("preprocessor", preprocessor),
    ("regression", clf)
]
model = PMMLPipeline(steps)

model.fit(X_train, y_train)

filename = "model.tmp"
sklearn2pmml(model, filename)
```

Versions:

```
Java: openjdk-11-jre on Debian Buster
sklearn: 0.24.2
sklearn_pandas: 2.2.0
sklearn2pmml: 0.71.1
```

**Comment by vruusmann** [comment]
Thanks for the reproducible test case. I love when I can copy&paste the test case code directly, and run it myself to see it all myself.

Didn't even have to add any imports!

> This is a minimal reproducible model that results in error. 

This issue appears to be about the `OneHotEncoder.drop_idx` attribute. This is a non-null list of integers, but one of the list elements itself is null. This is unexpected for SkLearn2PMML.

 > The only think I can think of is that I have categorical columns that are always 0/false

Could be the likely root cause.

I'll check.

**Comment by MattShirley** [comment]
@vruusmann wow, thank you so much for this quick resolution. I have built `jpmml-sklearn` locally and verified your latest commit fixes the issue and produces a PMML file using the command line version.

Do you have an expected timeline for releasing this on PyPI/Maven? Or alternatively, is there a way to use a locally built JAR file with `sklearn2pmml`? Apologies, I don't have very much experience with Java. I'd also like to not have to modify the `sklearn2pmml` repo locally if necessary.

**Comment by vruusmann** [comment]
> Do you have an expected timeline for releasing this on PyPI/Maven?

This is the single new commit since 0.71.1 - need several more to warrant a release. The schedule is unclear.

> is there a way to use a locally built JAR file with sklearn2pmml? 

JAR files reside in the `sklearn2pmml.resources` directory:
https://github.com/jpmml/sklearn2pmml/tree/0.71.1/sklearn2pmml/resources

The list of JAR files to use is specified in the `classpath.txt` file:
https://github.com/jpmml/sklearn2pmml/blob/0.71.1/sklearn2pmml/resources/classpath.txt

Now, to perform a JPMML-SkLearn library update you'd need to do the following:

1. Build a `jpmml-sklearn-1.6-SNAPSHOT.jar` JAR file, and copy it to the `sklearn2pmml/resources` directory of your SkLearn2PMML package directory.
2. Open `classpath.txt` in a text editor and replace the `jpmml-sklearn-1.6.18.jar` line with the `jpmml-sklearn-1.6-SNAPSHOT.jar` line.
3. Congratulate yourself.

**Comment by MattShirley** [comment]
@vruusmann thank you for this note, using the local JAR works great for me in the short term.
