### ISSUE TITLE
Support for `OrdinalEncoder.handle_unknown` attribute

### ISSUE THREAD

**Issue by kornilcdima** [jpmml/sklearn2pmml#289]
Hey,
I have an issue with dumping sklearn-pipeline to pmml. The problem is with argument of OrdinalEncoder **handle_unknown='return_nan'**. This argument is new and appeared in scikit-learn 0.24.
Do you have any guess how to solve it?

My code:
```
#sklearn2pmml==0.73.0
#scikit-learn==0.24.2
from sklearn2pmml import make_pmml_pipeline, sklearn2pmml
from sklearn.impute import SimpleImputer

oe_cols = ['netspeed', 'sspId', 'videoOrientation']
LGBM = lgb.LGBMRegressor(**params)

preprocessor = ColumnTransformer(
    transformers=[
        ('OE', OrdinalEncoder(handle_unknown='return_nan'), oe_cols)
        ], remainder='passthrough')


y = data['bidprice'].values.reshape(-1, 1)

clf = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', LGBM)])

clf.fit(data[cols], np.log(y))

pmml_pipeline = make_pmml_pipeline(clf)
sklearn2pmml(pmml_pipeline, "./ios-us-lgbm.pmml")
```

That throws an error:
```
Standard output is empty
Standard error:
июн 30, 2021 12:53:13 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
июн 30, 2021 12:53:13 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 35 ms.
июн 30, 2021 12:53:13 PM org.jpmml.sklearn.Main run
INFO: Converting PKL to PMML..
июн 30, 2021 12:53:13 PM sklearn2pmml.pipeline.PMMLPipeline initTargetFields
WARNING: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
июн 30, 2021 12:53:13 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert PKL to PMML
java.lang.IllegalArgumentException: return_nan
	at category_encoders.OrdinalEncoder.encodeFeatures(OrdinalEncoder.java:68)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.compose.ColumnTransformer.encodeFeatures(ColumnTransformer.java:63)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:212)
	at org.jpmml.sklearn.Main.run(Main.java:226)
	at org.jpmml.sklearn.Main.main(Main.java:143)

Exception in thread "main" java.lang.IllegalArgumentException: return_nan
	at category_encoders.OrdinalEncoder.encodeFeatures(OrdinalEncoder.java:68)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.compose.ColumnTransformer.encodeFeatures(ColumnTransformer.java:63)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:212)
	at org.jpmml.sklearn.Main.run(Main.java:226)
	at org.jpmml.sklearn.Main.main(Main.java:143)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-107-7081cbd487b5> in <module>
      2 
      3 pmml_pipeline = make_pmml_pipeline(clf)
----> 4 sklearn2pmml(pmml_pipeline, "./ios-us-lgbm.pmml")

~/prod_env/lib/python3.7/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    256                                 print("Standard error is empty")
    257                 if retcode:
--> 258                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    259         finally:
    260                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

**Comment by vruusmann** [comment]
> The problem is with argument of OrdinalEncoder handle_unknown='return_nan'

As of 0.24(.2), the `sklearn.preprocessing.OrdinalEncoder.handle_unknown` supports two values - `error` and `use_encoded_value`. There is no `return_nan` option.

> Exception in thread "main" java.lang.IllegalArgumentException: return_nan
>   at category_encoders.OrdinalEncoder.encodeFeatures(OrdinalEncoder.java:68)

Go fix your Python imports - your pipeline is using `category_encoders.OrdinalEncoder` (not `sklearn.preprocesing.OrdinalEncoder`).

> Do you have any guess how to solve it?

Use `sklearn2pmml.decoration.Domain` decorator classes to set up proper invalid handling - define which values are invalid, and what to do about them. In the current case, looks like you're trying to map them to missing values.

Something like this:
```python
from sklearn2pmml.decoration import CategoricalDomain

domain = CategoricalDomain(invalid_value_treatment = "as_missing")
```

Encoding missing values as `NaN` is a poor surrogate for the above.

**Comment by kornilcdima** [comment]
Thank you a lot, I didn't notice that I imported OrdinalEncoder not from sklearn.
