### ISSUE TITLE
`OrdinalEncoder` fails to detect column data type when missing values are present

### ISSUE THREAD

**Issue by kornilcdima** [jpmml/sklearn2pmml#291]
Hey, I faced a problem, I couldn't dump sklearn-pipeline to pmml because of missing values. 
When I fill missing values, everything works fine. However, this solution is not for me, cause I won't have an option to fill missing values in the same manner on production. I tried both lightgbm and xgboost. The error stays the same.

Could you suggest something?
versions:
```
scikit-learn==0.24.2
pandas==1.2.5
numpy==1.17.4
scipy==1.7.0
lightgbm==3.2.1
xgboost==1.4.2
sklearn2pmml==0.73.0
```

I use this code:
```
cat_cols, num_cols, bool_cols = self.__class__.get_dtypes(X)
model = lgb.LGBMRegressor(**self.model_hyperprams)

cat_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy="constant", missing_values="-1")),
    ('oe', OrdinalEncoder(handle_unknown='use_encoded_value',
                          unknown_value=-1))])

num_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
])

transformers = [(f'{i}_tr', cat_transformer, [i]) for i in cat_cols] \
               + [(f'{i}_tr', num_transformer, [i]) for i in num_cols]

preprocessor = ColumnTransformer(transformers=transformers,
                                 remainder='passthrough')

pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                           ('model', model)])

pipeline.fit(X, y)

pmml_pipeline = make_pmml_pipeline(pipeline, target_fields=[m.target])
sklearn2pmml(pmml_pipeline, "./data/temp.pmml", with_repr=True, debug=False)
```

if I do manual replacing missing values, everything works
```
def fill_missing_values(df):
    df = copy.deepcopy(df)
    for col in df.select_dtypes(include='object').columns:
        df[col] = df[col].fillna('-1')
    for col in df.select_dtypes(include='integer').columns:
        df[col] = df[col].fillna(-1)
    for col in df.select_dtypes(include='float').columns:
        df[col] = df[col].fillna(-1.0)
    return df
```

Error:
```
Standard output is empty
Standard error:
июл 21, 2021 2:26:46 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
июл 21, 2021 2:26:46 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 60 ms.
июл 21, 2021 2:26:46 PM org.jpmml.sklearn.Main run
INFO: Converting PKL to PMML..
июл 21, 2021 2:26:46 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert PKL to PMML
java.lang.IllegalArgumentException
	at org.jpmml.converter.TypeUtil.getDataType(TypeUtil.java:57)
	at org.jpmml.converter.TypeUtil.getDataType(TypeUtil.java:114)
	at sklearn.preprocessing.OrdinalEncoder.getDataType(OrdinalEncoder.java:54)
	at sklearn.Transformer.updateFeatures(Transformer.java:79)
	at sklearn.Transformer.encode(Transformer.java:68)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn.pipeline.PipelineTransformer.encodeFeatures(PipelineTransformer.java:65)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.compose.ColumnTransformer.encodeFeatures(ColumnTransformer.java:63)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:212)
	at org.jpmml.sklearn.Main.run(Main.java:226)
	at org.jpmml.sklearn.Main.main(Main.java:143)

Exception in thread "main" java.lang.IllegalArgumentException
	at org.jpmml.converter.TypeUtil.getDataType(TypeUtil.java:57)
	at org.jpmml.converter.TypeUtil.getDataType(TypeUtil.java:114)
	at sklearn.preprocessing.OrdinalEncoder.getDataType(OrdinalEncoder.java:54)
	at sklearn.Transformer.updateFeatures(Transformer.java:79)
	at sklearn.Transformer.encode(Transformer.java:68)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn.pipeline.PipelineTransformer.encodeFeatures(PipelineTransformer.java:65)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.compose.ColumnTransformer.encodeFeatures(ColumnTransformer.java:63)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:212)
	at org.jpmml.sklearn.Main.run(Main.java:226)
	at org.jpmml.sklearn.Main.main(Main.java:143)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_3040/3310494021.py in <module>
----> 1 sklearn2pmml(pmml_pipeline, "./data/temp.pmml", with_repr=True, debug=False)

~/prod_env/lib/python3.7/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    256                                 print("Standard error is empty")
    257                 if retcode:
--> 258                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    259         finally:
    260                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

**Comment by vruusmann** [comment]
The JPMML-SkLearn library is trying to determine the data type of a feature column by inspecting the `OrdinalEncoder.categories_` attribute.

This is a list of valid category levels. It is assumed that all values have the same data type, and that there are no missing values (ie. `None` values) in there.

The above assumption fails in your case. What is the cause - mixed data type values, or a `None` value? Can you print & attach the content of your `OrdinalEncoder.categories_` attribute?

**Comment by vruusmann** [comment]
Both LightGBM and XGBoost provide native support for missing values. If you substitute missing values during data pre-processing, then you are actually depriving the final estimator from important information, and therefore intentionally degrading its predictive performance.

Consider replacing `sklearn.preprocessing.OrdinalEncoder` with some missing value-aware encoder.
