### ISSUE TITLE
Bitwise or in ExpressionTransformer 

### ISSUE THREAD

**Issue by mkuiack** [jpmml/sklearn2pmml#304]
I'm writing a feature generation preprocessing step which checks if a value is close to being a round factor of 10, using the ExpressionTransformer

```python 
feature_5 = DataFrameMapper([
    (["Amount_Usd"],
     [Alias(ExpressionTransformer("1 if ((X[0] % 10.) <= 0.1) | ((X[0] % 10.) >= 9.9) else 0"), 
            name="feature_5", prefit=True)],)
])
```
```python
feature_5

DataFrameMapper(drop_cols=[],
                features=[(['Amount_Usd'],
                           [Alias(name='feature_5', prefit=True,
                                  transformer=ExpressionTransformer(expr='1 if '
                                                                         '((X[0] '
                                                                         '% '
                                                                         '10.) '
                                                                         '<= '
                                                                         '0.1) '
                                                                         '| '
                                                                         '((X[0] '
                                                                         '% '
                                                                         '10.) '
                                                                         '>= '
                                                                         '9.9) '
                                                                         'else '
                                                                         '0'))])])
```

The expression is valid python, but there seems to be an issue with the translation of | to LogicalOr? 

> SEVERE: Failed to convert PKL to PMML
org.jpmml.python.TokenMgrException: Lexical error at line 1, column 28.  Encountered: "|" (124), after : ""
	at org.jpmml.python.ExpressionTranslatorTokenManager.getNextToken(ExpressionTranslatorTokenManager.java:619)
	at org.jpmml.python.ExpressionTranslator.jj_scan_token(ExpressionTranslator.java:1967)
	at org.jpmml.python.ExpressionTranslator.jj_3R_TrailerFunctionInvocationExpression_745_9_59(ExpressionTranslator.java:1182)
	at org.jpmml.python.ExpressionTranslator.jj_3R_PrimaryExpression_634_58_44(ExpressionTranslator.java:1386)
	at org.jpmml.python.ExpressionTranslator.jj_3R_PrimaryExpression_634_58_35(ExpressionTranslator.java:1377)
	at org.jpmml.python.ExpressionTranslator.jj_3R_PrimaryExpression_634_17_28(ExpressionTranslator.java:1581)
	at org.jpmml.python.ExpressionTranslator.jj_3R_PrimaryExpression_623_9_26(ExpressionTranslator.java:1633)
	at org.jpmml.python.ExpressionTranslator.jj_3R_UnaryExpression_605_17_25(ExpressionTranslator.java:1651)
	at org.jpmml.python.ExpressionTranslator.jj_3R_UnaryExpression_600_9_20(ExpressionTranslator.java:1697)
	at org.jpmml.python.ExpressionTranslator.jj_3R_MultiplicativeExpression_587_9_15(ExpressionTranslator.java:1732)
	at org.jpmml.python.ExpressionTranslator.jj_3R_AdditiveExpression_563_9_12(ExpressionTranslator.java:1124)
	at org.jpmml.python.ExpressionTranslator.jj_3_1(ExpressionTranslator.java:1174)
	at org.jpmml.python.ExpressionTranslator.jj_2_1(ExpressionTranslator.java:1069)
	at org.jpmml.python.ExpressionTranslator.ComparisonExpression(ExpressionTranslator.java:398)
	at org.jpmml.python.ExpressionTranslator.NegationExpression(ExpressionTranslator.java:387)
	at org.jpmml.python.ExpressionTranslator.LogicalAndExpression(ExpressionTranslator.java:357)
	at org.jpmml.python.ExpressionTranslator.LogicalOrExpression(ExpressionTranslator.java:336)
	at org.jpmml.python.ExpressionTranslator.IfElseExpression(ExpressionTranslator.java:317)
	at org.jpmml.python.ExpressionTranslator.Expression(ExpressionTranslator.java:310)
	at org.jpmml.python.ExpressionTranslator.IfElseExpression(ExpressionTranslator.java:321)
	at org.jpmml.python.ExpressionTranslator.Expression(ExpressionTranslator.java:310)
	at org.jpmml.python.ExpressionTranslator.translateExpressionInternal(ExpressionTranslator.java:304)
	at org.jpmml.python.ExpressionTranslator.translate(ExpressionTranslator.java:34)
	at org.jpmml.python.ExpressionTranslator.translate(ExpressionTranslator.java:23)
	at sklearn2pmml.preprocessing.ExpressionTransformer.encodeFeatures(ExpressionTransformer.java:52)
	at sklearn2pmml.decoration.Alias.encodeFeatures(Alias.java:56)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
	at sklearn.Initializer.encodeFeatures(Initializer.java:48)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.pipeline.FeatureUnion.encodeFeatures(FeatureUnion.java:45)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:211)
	at org.jpmml.sklearn.Main.run(Main.java:226)
	at org.jpmml.sklearn.Main.main(Main.java:143)

**Comment by mkuiack** [comment]
I've changing the expression to 
```python 
1 if ((X[0] % 10.) <= 0.1) or ((X[0] % 10.) >= 9.9) else 0
```

This solved the issue with sklearn2pmml, but in python this expression would return 
>ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
