### ISSUE TITLE
Using `DataFrameMapper` in the middle of pipeline

### ISSUE THREAD

**Issue by dev26** [jpmml/sklearn2pmml#316]
I have created a pmml pipeline in which two dataframemappers are placed. The second dataframemapper uses the output of the first dataframemapper. The pipeline was successfully built and working correctly. Below is the code in which **add_one_mapper** is first dataframemapper and **add_one_mapper_2** is second dataframemapper-

```python
pipeline = PMMLPipeline(steps = [('mapper1', add_one_mapper),('mapper2', add_one_mapper_2)])
pipeline.fit_transform(specs_ready)
```

But when I ran the last step which was to use sklearn2pmml it was throwing an error.
```pythion
sklearn2pmml(pipeline, "/users/XGBoost.pmml")`
```
Below is the error which I am getting. 
```
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/usr/lib/python3.8/subprocess.py:853: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
Standard output is empty
Standard error:
Feb 24, 2022 5:31:55 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Feb 24, 2022 5:31:55 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 40 ms.
Feb 24, 2022 5:31:55 PM org.jpmml.sklearn.Main run
INFO: Converting..
Feb 24, 2022 5:31:55 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: Transformer 'sklearn_pandas.dataframe_mapper.DataFrameMapper' must be the first step of the pipeline
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:118)
	at sklearn.Composite.encodeFeatures(Composite.java:129)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:209)
	at org.jpmml.sklearn.Main.run(Main.java:228)
	at org.jpmml.sklearn.Main.main(Main.java:148)

Exception in thread "main" java.lang.IllegalArgumentException: Transformer 'sklearn_pandas.dataframe_mapper.DataFrameMapper' must be the first step of the pipeline
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:118)
	at sklearn.Composite.encodeFeatures(Composite.java:129)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:209)
	at org.jpmml.sklearn.Main.run(Main.java:228)
	at org.jpmml.sklearn.Main.main(Main.java:148)
```

Please tell me what is needed to remove this error.
Thanks

**Comment by vruusmann** [comment]
> Please tell me what is needed to remove this error.

- Combine these two `DataFrameMapper` objects into one.
- Use a `sklearn.compose.ColumnTransformer` in place of the second `DataFrameMapper`.
