### ISSUE TITLE
FunctionTransformer serialization problems

### ISSUE THREAD

**Issue by ColdTeapot273K** [jpmml/sklearn2pmml#323]
Spec:
- Python 3.9.9
- [GCC 7.3.1 20180712 (Red Hat 7.3.1-13)] on linux
- scikit-learn         1.0.2 
- sklearn2pmml         0.79.0 
- pandas               1.4.2 
- numpy                1.22.3 

---

Hello,
I've came across a problem while trying to serialize `sklearn` `FunctionTransformer` with custom callback (which serializes just fine via python's `joblib` btw). Not all too surprised but I wonder what are the possible solutions to this if any. Or at least to this particular type of transformation (concatenating column values into a new column).

---
Code to reproduce and the error:

```python
import pandas as pd
import numpy as np

from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer

from sklearn2pmml import sklearn2pmml
from sklearn2pmml.pipeline import PMMLPipeline

df = pd.DataFrame({"col_1": [1, 2, 3], "col_2": [1, 2, 3]})

def concat(df):
    df_out = df.copy()
    df_out["concat"] = df_out["col_1"].astype(str) + df_out["col_2"].astype(str) + "A"
    return df_out


transformer = FunctionTransformer(concat)
transformer.fit_transform(df)

ct = ColumnTransformer([("transformer", transformer, ["col_1", "col_2"])])

pipeline = PMMLPipeline([("ct", ct)])

pipeline.fit_transform(df)
# array([[1, 1, '11A'],
#        [2, 2, '22A'],
#        [3, 3, '33A']], dtype=object)

sklearn2pmml(pipeline, "pipeline" + ".pmml")
```

The error is raised at the final line. The Java stack trace is as follows:
```java
Standard output is empty
Standard error:
Exception in thread "main" java.lang.IllegalArgumentException: Attribute 'sklearn.preprocessing._function_transformer.FunctionTransformer.func' has an unsupported value (Python class __main__.concat)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:47)
	at org.jpmml.python.PythonObject.get(PythonObject.java:104)
	at org.jpmml.python.PythonObject.getOptional(PythonObject.java:114)
	at sklearn.preprocessing.FunctionTransformer.getFunc(FunctionTransformer.java:68)
	at sklearn.preprocessing.FunctionTransformer.encodeFeatures(FunctionTransformer.java:44)
	at sklearn.Transformer.encode(Transformer.java:69)
	at sklearn.compose.ColumnTransformer.encodeFeatures(ColumnTransformer.java:62)
	at sklearn.Transformer.encode(Transformer.java:69)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:211)
	at com.sklearn2pmml.Main.run(Main.java:84)
	at com.sklearn2pmml.Main.main(Main.java:62)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDictConstructor to org.jpmml.python.Identifiable
	at java.base/java.lang.Class.cast(Class.java:3816)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:45)
	... 11 more
```

**Comment by vruusmann** [comment]
The pickled representation of your `FunctionTransformer` object only contains the name of the function (`__main__.concat`). It does not contain its body.

If this pipeline is unpickled into pristine Python environment, then the `(PMML)Pipeline.transform(X)` method won't be able to complete.

Sample scipt:
```python
import pandas as pd

import joblib

df = pd.DataFrame({"col_1": [1, 2, 3], "col_2": [1, 2, 3]})

pipeline = joblib.load("pipeline.pkl")
pipeline.transform(X)
```

Python error:
```
Traceback (most recent call last):
  File "step2.py", line 7, in <module>
    pipeline = joblib.load("pipeline.pkl")
  File "/usr/local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/usr/local/lib/python3.7/pickle.py", line 1085, in load
    dispatch[key[0]](self)
  File "/usr/local/lib/python3.7/pickle.py", line 1373, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/lib/python3.7/pickle.py", line 1427, in find_class
    return getattr(sys.modules[module], name)
AttributeError: module '__main__' has no attribute 'concat'
```

The pickling of lambdas fails right away, because lambdas don't even have a pickling-worthy name. The pickling of locally defined (named-) functions appears to succeed, but it's still a mirage.

**Comment by vruusmann** [comment]
> Or at least to this particular type of transformation (concatenating column values into a new column).
> ```python
> df_out["concat"] = df_out["col_1"].astype(str) + df_out["col_2"].astype(str) + "A"
> ```

For casting, you can use `sklearn2pmml.preprocessing.CastTransformer`. For string concatenation you can use `sklearn2pmml.preprocessing.ConcatTransformer` or good old `sklearn2pmml.preprocessing.ExpressionTransformer`.

The simplest sub-pipeline that mimics your `__main__.concat` function:
```python
concatter = make_pipeline([CastTransformer(dtype = str), ExpressionTransformer("X['col_1'] + X['col_2'] + 'A'")])
```

**Comment by liuhuanshuo** [comment]
Thank you for your reply, I am aware of this, but even if I did not use the lambda function, it would not work.

Here's my function code, which doesn't work either
```
def transform_channel_ty_cd(X):
    
    res = []
    
    for i in range(len(X)):
        
        if X[i] in  all_cate_dict['channel_type_cd_3']:
            res.append(all_cate_dict['channel_type_cd_3'].get(X[i]))
        else:
            res.append(0)
            
    return pd.DataFrame(res)
```
