### ISSUE TITLE
Verification of multi-output models

### ISSUE THREAD

**Issue by Rajeshyd0308** [jpmml/sklearn2pmml#348]
Hello Villu,
I'm having trouble creating a pmml file, while using a multioutput regressor.

```python
import numpy as np
import pandas as pd
import pickle
from sklearn2pmml import PMMLPipeline, sklearn2pmml
from sklearn2pmml.decoration import ContinuousDomain
from sklearn_pandas import DataFrameMapper
from sklearn2pmml import sklearn2pmml
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn2pmml.preprocessing import ExpressionTransformer
from xgboost import XGBRegressor

def main():

    train_df, targets_df, features  = load_dataset()
    ##### load mapper #####
    with open("numerical_mapper.pkl", 'rb') as mapper_numerical_pkl:
        mapper_numerical = pickle.load(mapper_numerical_pkl)
    with open('categorical_mapper.pkl', 'rb') as mapper_categorical_pkl:
        mapper_categorical = pickle.load(mapper_categorical_pkl)

    mapper = mapper_numerical + mapper_categorical
    mapper = [item for item in mapper if item[0][0] in features]
    print(train_df.shape, targets_df.shape)
    # model = XGBRegressor()
    model = MultiOutputRegressor(XGBRegressor(objective='reg:squarederror'))

    ##### build pipeline #####
    pipeline = PMMLPipeline([
        ('mapper', DataFrameMapper(mapper)),
        ('clf', model)
    ])
    
    pipeline.fit(train_df, targets_df)
    
    pipeline.verify(train_df.sample(n = 15))
    ##### save pipeline #####
    with open("output_pkl", 'wb') as f:
        pickle.dump(pipeline, f)
        
    sklearn2pmml(pipeline, "pipeline_exp1.pmml")
##### record end time #####
if __name__=="__main__":
    main()
```
When I run this I get:

```
(4973, 250) (4973, 3)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xgboost/core.py:614: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  "because it will generate extra copies and increase memory consumption")
Standard output is empty
Standard error:
Exception in thread "main" java.lang.ClassCastException: org.jpmml.converter.MultiLabel cannot be cast to org.jpmml.converter.ScalarLabel
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:341)
	at com.sklearn2pmml.Main.run(Main.java:91)
	at com.sklearn2pmml.Main.main(Main.java:66)

Traceback (most recent call last):
  File "test_pipeline_original_data.py", line 85, in <module>
    main()
  File "test_pipeline_original_data.py", line 82, in main
    sklearn2pmml(pipeline, "pipeline_exp_single.pmml")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn2pmml/__init__.py", line 286, in sklearn2pmml
    raise RuntimeError("The SkLearn2PMML application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
RuntimeError: The SkLearn2PMML application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```
My library versions are:
sklearn2pmml==0.86.3
xgboost==0.90
scikit-learn==0.24.2
python==3.6.6

**Comment by vruusmann** [comment]
> Exception in thread "main" java.lang.ClassCastException: org.jpmml.converter.MultiLabel cannot be cast to 
> org.jpmml.converter.ScalarLabel
>	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:341)

Model verification does not work with multi-output models yet.

Simply leave out `PMMLPipeline.verify(X)`, and the conversion should succeed.

**Comment by Rajeshyd0308** [comment]
Thank you for the swift response. It worked!
