### ISSUE TITLE
sklearn2pmml fails to create pmml for XGBoost model

### ISSUE THREAD

**Issue by gaurbans** [jpmml/sklearn2pmml#381]
I'm trying to create a pmml file for a XGBoost model and I'm getting the error below. I don't get this error if I use sklearn2pmml to create a pmml file for a sklearn LogisticRegression model. What could be the problem for XGBoost? I'm using `scikit-learn` version 1.0.2, `sklearn2pmml` version 0.77.0 and `xgboost` version 1.6.2. 

```
from xgboost import XGBClassifier
from sklearn2pmml.pipeline import PMMLPipeline
from sklearn2pmml import sklearn2pmml

pipeline = PMMLPipeline([("classifier", XGBClassifier(random_state=42))])
pipeline.fit(pd.DataFrame(X_processed, columns=feature_names), pd.DataFrame(y_train))
sklearn2pmml(pipeline, os.path.join(artifact_path, "model.pmml"))

Standard output is empty
Standard error:
May 25, 2023 1:45:35 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
May 25, 2023 1:45:35 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 20 ms.
May 25, 2023 1:45:35 PM org.jpmml.sklearn.Main run
INFO: Converting PKL to PMML..
May 25, 2023 1:45:35 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert PKL to PMML
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 18 path $.L-Config
        at com.google.gson.internal.Streams.parse(Streams.java:60)
        at com.google.gson.JsonParser.parseReader(JsonParser.java:85)
        at com.google.gson.JsonParser.parseReader(JsonParser.java:60)
        at com.google.gson.JsonParser.parse(JsonParser.java:104)
        at org.jpmml.xgboost.Learner.loadJSON(Learner.java:218)
        at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:90)
        at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:60)
        at xgboost.sklearn.Booster.loadLearner(Booster.java:52)
        at xgboost.sklearn.Booster.getLearner(Booster.java:42)
        at xgboost.sklearn.BoosterUtil.getLearner(BoosterUtil.java:103)
        at xgboost.sklearn.BoosterUtil.getObjFunction(BoosterUtil.java:62)
        at xgboost.sklearn.XGBClassifier.checkLabel(XGBClassifier.java:48)
        at sklearn.Estimator.encode(Estimator.java:100)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:233)
        at org.jpmml.sklearn.Main.run(Main.java:217)
        at org.jpmml.sklearn.Main.main(Main.java:143)
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 18 path $.L-Config
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:529)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:424)
        at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661)
        at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:684)
        at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655)
        at com.google.gson.internal.Streams.parse(Streams.java:48)
        ... 15 more

Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 18 path $.L-Config
        at com.google.gson.internal.Streams.parse(Streams.java:60)
        at com.google.gson.JsonParser.parseReader(JsonParser.java:85)
        at com.google.gson.JsonParser.parseReader(JsonParser.java:60)
        at com.google.gson.JsonParser.parse(JsonParser.java:104)
        at org.jpmml.xgboost.Learner.loadJSON(Learner.java:218)
        at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:90)
        at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:60)
        at xgboost.sklearn.Booster.loadLearner(Booster.java:52)
        at xgboost.sklearn.Booster.getLearner(Booster.java:42)
        at xgboost.sklearn.BoosterUtil.getLearner(BoosterUtil.java:103)
        at xgboost.sklearn.BoosterUtil.getObjFunction(BoosterUtil.java:62)
        at xgboost.sklearn.XGBClassifier.checkLabel(XGBClassifier.java:48)
        at sklearn.Estimator.encode(Estimator.java:100)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:233)
        at org.jpmml.sklearn.Main.run(Main.java:217)
        at org.jpmml.sklearn.Main.main(Main.java:143)
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 18 path $.L-Config
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:529)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:424)
        at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661)
        at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:684)
        at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655)
        at com.google.gson.internal.Streams.parse(Streams.java:48)
        ... 15 more

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-62-e97163335b23> in <module>
      5 pipeline = PMMLPipeline([("classifier", XGBClassifier(random_state=42))])
      6 pipeline.fit(pd.DataFrame(X_processed, columns=feature_names), pd.DataFrame(y_train))
----> 7 sklearn2pmml(pipeline, os.path.join(artifact_path, "model.pmml"))

~\AppData\Local\Continuum\anaconda3\envs\mql37\lib\site-packages\sklearn2pmml\__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    256                                 print("Standard error is empty")
    257                 if retcode:
--> 258                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    259         finally:
    260                 if debug:
 
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

**Comment by vruusmann** [comment]
> sklearn2pmml version 0.77.0 and xgboost version 1.6.2

SkLearn2PMML 0.77.0 was released in December 2021, whereas XGBoost 1.6.2 was released in August 2022 (ie. nine months later). One of the key features of XGBoost 1.6.X is that models are now serialized in UBSJON data format (binary JSON).

Now, can you put those two pieces of information together, and make a guess why your setup doesn't work?

If not, then simply please upgrade to the latest SkLearn2PMML package version (as of today, that would be 0.92.2).
