### ISSUE TITLE
looking for support on quantile_forest for RandomForestQuantileRegressor

### ISSUE THREAD

**Issue by akashkumar398** [jpmml/sklearn2pmml#392]
```
Standard output is empty
Standard error:
Exception in thread "main" net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for quantile_forest._quantile_forest_fast.QuantileForest). This happens when an unsupported/unregistered class is being unpickled that requires construction arguments. Fix it by registering a custom IObjectConstructor for this class.
	at net.razorvine.pickle.objects.ClassDictConstructor.construct(ClassDictConstructor.java:23)
	at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:759)
	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:199)
	at org.jpmml.python.CustomUnpickler.dispatch(CustomUnpickler.java:32)
	at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:65)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:109)
	at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:86)
	at com.sklearn2pmml.Main.run(Main.java:75)
	at com.sklearn2pmml.Main.main(Main.java:65)
```

**Comment by vruusmann** [comment]
Must be this 3rd-party extension package: https://github.com/zillow/quantile-forest

Looks too "fringe" (less than GH 50 stars) - will be spending my focus/time elsewhere.

**Comment by abanerjee033** [comment]
Even I'm facing the same issue. It would be great to include the conversion of Quantile regressor into sklearn2pmml package.
I've used Ridge, LinearRegression and Quantile regression for a use case and Quantile gave me better results. It also has the capability to generate Quantile Percentile results which helps to give ranges in a prediction like (0.025, 0.5, 0.975).
