### ISSUE TITLE
error msg when converting randomforest to pmml

### ISSUE THREAD

**Issue by premiumy** [jpmml/sklearn2pmml#4]
I've got errors when converting the example randomforest to pmml (the last step).  Can you help me out?

my code:

```
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
import pandas
import sklearn_pandas
from sklearn.ensemble.forest import RandomForestClassifier
from sklearn2pmml import sklearn2pmml

iris = load_iris()
iris_df = pandas.concat((pandas.DataFrame(iris.data[:, :], columns = ["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"]), pandas.DataFrame(iris.target, columns = ["Species"])), axis = 1)
iris_mapper = sklearn_pandas.DataFrameMapper([
    (["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"], PCA(n_components = 3)),
    ("Species", None)
])

iris = iris_mapper.fit_transform(iris_df)

iris_X = iris[:, 0:3]
iris_y = iris[:, 3]

iris_forest = RandomForestClassifier(min_samples_leaf = 5)
iris_forest.fit(iris_X, iris_y)

sklearn2pmml(iris_forest, iris_mapper, "forest.pmml")
```
the error msg:
```
Exception in thread "main" java.lang.StackOverflowError
	at sun.misc.FDBigInteger.leftShift(Unknown Source)
	at sun.misc.FDBigInteger.valueOfPow52(Unknown Source)
	at sun.misc.FloatingDecimal$BinaryToASCIIBuffer.dtoa(Unknown Source)
	at sun.misc.FloatingDecimal$BinaryToASCIIBuffer.access$100(Unknown Source)
	at sun.misc.FloatingDecimal.getBinaryToASCIIConverter(Unknown Source)
	at sun.misc.FloatingDecimal.getBinaryToASCIIConverter(Unknown Source)
	at sun.misc.FloatingDecimal.toJavaFormatString(Unknown Source)
	at java.lang.Double.toString(Unknown Source)
	at org.jpmml.converter.ValueUtil.formatValue(ValueUtil.java:118)
	at sklearn.tree.TreeModelUtil.encodeNode(TreeModelUtil.java:81)
	at sklearn.tree.TreeModelUtil.encodeNode(TreeModelUtil.java:96)
	at sklearn.tree.TreeModelUtil.encodeNode(TreeModelUtil.java:96)
	at sklearn.tree.TreeModelUtil.encodeNode(TreeModelUtil.java:96)
	at sklearn.tree.TreeModelUtil.encodeNode(TreeModelUtil.java:96)
```

**Comment by vruusmann** [comment]
Just tested - your code works without problems in my computer.

The exception occurs deep inside Java libraries. One would expect the method `sun.misc.FDBigInteger#valueOfPow52(...)` to fail more "intelligently", not by throwing StackOverflowError.

What is your Java version?
```
$ java -version
```

Also, can you dump your Random Forest model to a pickle file and share it with me?

**Comment by premiumy** [comment]
Thanks for reminding me of the java version.  When I downgraded from java 1.8 to java 1.7.0_67, it works.  Very good library to generate pmml.

**Comment by vruusmann** [comment]
What was the version of the "broken" Java installation (as indicated by `java -version`)?

The following Java versions appear to be functioning all good in my tests:
* OracleJDK: `1.8.0_05`, `1.8.0_31` `1.8.0_40`, `1.8.0_60`
* OpenJDK: `1.8.0_71`

**Comment by vruusmann** [comment]
Apparently, this StackOverflowError happens when unpickling 32-bit Python pickle files on a 64-bit Java: https://github.com/jpmml/jpmml-converter/issues/4

The solution is to upgrade to 64-bit Python. Technically, it should be possible to add support for 32-bit Python pickle files, but it's not a priority.
