### ISSUE TITLE
sklearn2pmml does not work with sklearn version 1.3.0 and newer

### ISSUE THREAD

**Issue by fritshermans** [jpmml/sklearn2pmml#401]
When I try the example as shown in the README of this repo using sklearn version 1.3.0 (or 1.3.2), I get the following error:

```
Standard output is empty
Standard error:
Exception in thread "main" java.lang.IllegalArgumentException
	at numpy.DType.toDescr(DType.java:88)
	at joblib.NumpyArrayWrapper.toArray(NumpyArrayWrapper.java:41)
	at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:76)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:109)
	at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:86)
	at com.sklearn2pmml.Main.run(Main.java:75)
	at com.sklearn2pmml.Main.main(Main.java:65)

Preserved dump file(s): /var/folders/53/cmk0glys5jg0wwrlp1676gh40000gq/T/estimator-7x5v1m22.pkl.z
```
When I downgrade sklearn to version 1.2.2, everything works fine. It would be nice if the package works with the latest version of sklearn.

**Comment by fritshermans** [comment]
This is the zipped pickle file created with sklearn version 1.3.0:
[estimator-p9w2g0bq.pkl.z.zip](https://github.com/jpmml/sklearn2pmml/files/13544678/estimator-p9w2g0bq.pkl.z.zip)

**Comment by fritshermans** [comment]
The data is the iris dataset so it is not sensitive. Here are the versions that I'm using:

```
python: 3.10.13
sklearn2pmml: 0.99.2
sklearn: 1.3.0
sklearn_pandas: 2.2.0
pandas: 2.1.3
numpy: 1.26.2
dill: 0.3.7
joblib: 1.3.2
java: 1.8.0_391
