### ISSUE TITLE
Using SelectorKBest with score function chi2

### ISSUE THREAD

**Issue by Fenn92** [jpmml/sklearn2pmml#78]
Hello, I'm trying to convert my SVM model to PMML using sklearn2pmml. Unfortunately I get the following exception: 
```
Jan 15, 2018 2:49:21 PM org.jpmml.sklearn.Main run
INFORMAZIONI: Parsing PKL..
Jan 15, 2018 2:49:21 PM org.jpmml.sklearn.Main run
INFORMAZIONI: Parsed PKL in 153 ms.
Jan 15, 2018 2:49:21 PM org.jpmml.sklearn.Main run
INFORMAZIONI: Converting..
Jan 15, 2018 2:49:21 PM org.jpmml.sklearn.Main run
GRAVE: Failed to convert
java.lang.UnsupportedOperationException
	at sklearn.Selector.getOpType(Selector.java:42)
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:144)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.UnsupportedOperationException
	at sklearn.Selector.getOpType(Selector.java:42)
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:144)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)`
```
using the following code:
```
    data_x = df[df.columns.difference([METHOD_NAME, TARGET_NAME])]
    data_y = df[TARGET_NAME]

    pipeline = PMMLPipeline([
        ("selector", SelectorProxy(SelectKBest(chi2, k = 150))),
        ("classifier", model)
    ])

    pipeline.fit(data_x, data_y)
    sklearn2pmml(pipeline, save_file, with_repr=True)
```
If I remove the 'selector' from the pipeline everthing works fine.
Any ideas why the `SelectKBest` gives me this error?

Versions:
```
sklearn 0.19.0
sklearn.externals.joblib 0.11
sklearn.pandas 1.6.0
sklearn2pmml 0.29.0
```
Thank you,
Darius

**Comment by vruusmann** [comment]
The first step of a PMML pipeline must be able to specify the initial "feature configuration" - how many features there are, what are their names, data and operational types. Selector classes do not have this ability. So, the conversion will always fail if the first step of a PMML pipeline is some selector (any Selector class, not just `SelectKBest`).

To solve this issue, please insert `sklearn_pandas.DataFrameMapper` into your PMML pipeline as the first step:
```Python
from sklearn_pandas import DataFrameMapper
from sklearn2pmml.decoration import ContinuousDomain

data_x = df[df.columns.difference([METHOD_NAME, TARGET_NAME])]
data_y = df[TARGET_NAME]

pipeline = PMMLPipeline([
  ("mapper", DataFrameMapper([
    # Assumes that all feature columns are continuous floats
    (data_x.columns.values, ContinuousDomain())
  ]))
  ("selector", SelectorProxy(SelectKBest(chi2, k = 150))),
  ("classifier", model)
])
```

**Comment by vruusmann** [comment]
Leaving this issue open.

The converter should nicely inform the end user if the initial "feature configuration" is missing and/or incomplete (instead of throwing an obscure `UnsupportedOperationException`).
