### ISSUE TITLE
IllegalArgumentException when using the same expression to transform multiple sets of features

### ISSUE THREAD

**Issue by rwjmiller** [jpmml/sklearn2pmml#85]
It was quite tricky to work out what was causing this. Fortunately, I've found a couple of workarounds, which are given below, but a fix would be appreciated. If that isn't feasible, please consider throwing a more specific type of exception when encountering duplicate expressions that are valid in isolation.

Reproduction steps:

```
from sklearn.dummy import DummyRegressor
from sklearn2pmml import PMMLPipeline, sklearn2pmml
from sklearn2pmml.preprocessing import ExpressionTransformer
from sklearn_pandas import DataFrameMapper
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(0,100,size=(10000, 6)), columns=list('ABCDEF'))

# Using the same expression to transform multiple sets of features results in an IllegalArgumentException
mapper = DataFrameMapper([
    (['A','B'], [ExpressionTransformer("X[:, 0] + X[:, 1]")],{"alias":"sum1"}),
    (['C','D'], [ExpressionTransformer("X[:, 0] + X[:, 1]")],{"alias":"sum2"})    
])

pipeline = PMMLPipeline([
    ("mapper", mapper),
    ("regressor", DummyRegressor())
])

pipeline.fit(df, df.F)
sklearn2pmml(pipeline, "pipeline_01.pmml", with_repr = True)
```
Error message:

```
Standard output is empty
Standard error:
Mar 01, 2018 1:12:24 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Mar 01, 2018 1:12:24 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 20 ms.
Mar 01, 2018 1:12:24 PM org.jpmml.sklearn.Main run
INFO: Converting..
Mar 01, 2018 1:12:24 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: eval(X[:, 0] + X[:, 1])
	at org.jpmml.converter.PMMLEncoder.checkName(PMMLEncoder.java:233)
	at org.jpmml.converter.PMMLEncoder.addDerivedField(PMMLEncoder.java:127)
	at org.jpmml.converter.PMMLEncoder.createDerivedField(PMMLEncoder.java:137)
	at org.jpmml.sklearn.SkLearnEncoder.createDerivedField(SkLearnEncoder.java:126)
	at sklearn2pmml.preprocessing.ExpressionTransformer.encodeFeatures(ExpressionTransformer.java:45)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
	at sklearn.Initializer.encodeFeatures(Initializer.java:53)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:147)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException: eval(X[:, 0] + X[:, 1])
	at org.jpmml.converter.PMMLEncoder.checkName(PMMLEncoder.java:233)
	at org.jpmml.converter.PMMLEncoder.addDerivedField(PMMLEncoder.java:127)
	at org.jpmml.converter.PMMLEncoder.createDerivedField(PMMLEncoder.java:137)
	at org.jpmml.sklearn.SkLearnEncoder.createDerivedField(SkLearnEncoder.java:126)
	at sklearn2pmml.preprocessing.ExpressionTransformer.encodeFeatures(ExpressionTransformer.java:45)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
	at sklearn.Initializer.encodeFeatures(Initializer.java:53)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:147)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-d248d6fdcc5c> in <module>()
     20 
     21 pipeline.fit(df, df.F)
---> 22 sklearn2pmml(pipeline, "pipeline_01.pmml", with_repr = True)

/opt/conda/lib/python3.6/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug)
    301                                 print("Standard error is empty")
    302                 if retcode:
--> 303                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    304         finally:
    305                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

Workarounds:

```
# Workaround 1: add or remove whitespace to make the expressions different
mapper = DataFrameMapper([
    (['A','B'], [ExpressionTransformer("X[:, 0] + X[:, 1]")],{"alias":"sum1"}),
    (['C','D'], [ExpressionTransformer("X[:, 0] + X[:, 1] ")],{"alias":"sum2"})    
])

pipeline = PMMLPipeline([
    ("mapper", mapper),
    ("regressor", DummyRegressor())
])

pipeline.fit(df, df.F)
sklearn2pmml(pipeline, "pipeline_02.pmml", with_repr = True)

# Workaround 2: add zero to make the expressions different
mapper = DataFrameMapper([
    (['A','B'], [ExpressionTransformer("X[:, 0] + X[:, 1]")],{"alias":"sum1"}),
    (['C','D'], [ExpressionTransformer("X[:, 0] + X[:, 1] + 0")],{"alias":"sum2"})    
])

pipeline = PMMLPipeline([
    ("mapper", mapper),
    ("regressor", DummyRegressor())
])

pipeline.fit(df, df.F)
sklearn2pmml(pipeline, "pipeline_03.pmml", with_repr = True)
```

**Comment by rwjmiller** [comment]
This appears to have the same underlying cause as another open issue:
https://github.com/jpmml/sklearn2pmml/issues/82

It could be avoided if there was some way of supplying a preferred name for the DerivedField produced by each ExpressionTransformer in the output PMML.

**Comment by vruusmann** [comment]
As a workaround, you should "mutate" the expression in a way that yields a different result when calling `repr(expression)`. Adding a `0` is definitely a valid mutation. However, a better alternative would have been to simply change the order of operands: `X[:, 0] + X[:, 1]` -> `X[:, 1] + X[:, 0]`.

The Scikit-Learn framework doesn't let one to attach arbitrary attributes to estimator and transformer objects (eg. a name hint attribute). I've been thinking about an approach, where there's a "wrapper" no-op transformer for renaming features:
```Python
from sklearn2pmml.decoration import Alias

mapper = DataFrameMapper([
    (['A','B'], Alias(ExpressionTransformer("X[:, 0] + X[:, 1]"), name = "sum1")),
    (['C','D'], Alias(ExpressionTransformer("X[:, 0] + X[:, 1] "), name = "sum2"))    
])
```

**Comment by rwjmiller** [comment]
On reflection I agree with AndreDCMartins (who reported #82)  - it would be much simpler from an end-user perspective if duplicate DerivedField names could be handled automatically at the point when PMML is generated, e.g. via incremental suffixes. 

The example I provided above produces a PMMLPipeline object that can apply the requested transformations correctly. Only the PMML conversion step fails. Would it be feasible to fix this issue within the java / PMML side of things, leaving the (already working) Python side untouched, or would that be a lot more work?

Also, I've encountered a third scenario which is affected by this issue: [cyclic encoding](http://blog.davidkaleko.com/feature-engineering-cyclical-features.html) for date and time related features.

This involves scaling the input variables into the (0, 1) range and then applying sin and cos transforms to them - the problem is that I have to do the scaling in two different ways for the sin and cos transforms in order to avoid duplicate DerivedFields.

**Comment by vruusmann** [comment]
> it would be much simpler from an end-user perspective if duplicate DerivedField names could be handled automatically

It's easy/convenient short-term, but it's costly long term. Instead of having auto-generated `DerivedField` element names with obscure prefixes and/or suffixes, it would be desirable to have explicit human-readable names there. These names are specified by the data scientist that trains the model, and consitutute a kind of "documentation" for it.

> I've encountered a third scenario which is affected by this issue: cyclic encoding for date and time related features.

Use child pipelines. Do the scaling, and then split the pipeline using the `sklearn.pipeline.FeatureUnion` - apply the `cos` transformation on one terminal, and the `sin` transformation on the other.

**Comment by rwjmiller** [comment]
I don't see much of a cost here - the generated DerivedField names appear only in PMML files that are seldom read by humans. Maybe it would be nice to have an alias transformer as well, but it's quite a bit of extra hassle.

I've tried splitting the pipeline in the way you suggest, but I'm not sure what names I should use to refer to the rescaled variables within the child sin and cos pipelines. An example would be helpful if you have one handy.

**Comment by vruusmann** [comment]
> What names I should use to refer to the rescaled variables...

Simply do `FunctionTransformer(numpy.cos)` and `FunctionTransformer(numpy.sin)`?

**Comment by rwjmiller** [comment]
Ok, so if I understand correctly, this is roughly what you had in mind, following on from the previous example? It seems to generate valid PMML at least.

```
from sklearn.preprocessing import MinMaxScaler, FunctionTransformer
from sklearn.cyclic_pipeline import FeatureUnion, Pipeline
from xgboost.sklearn import XGBRegressor

mapper = DataFrameMapper([
    (['A','B'],[MinMaxScaler(feature_range=(0,2*3.14159))])
])

cyclic_pipeline = PMMLPipeline([
    ("mapper", mapper),
    ("union", FeatureUnion([
        ("sin",FunctionTransformer(np.sin)),
        ("cos",FunctionTransformer(np.cos))
    ])),
    ("regressor", XGBRegressor())
])

cyclic_pipeline.fit(df, df.C)
sklearn2pmml(cyclic_pipeline,"pipeline_04.pmml")
```

**Comment by vruusmann** [comment]
> if I understand correctly, this is roughly what you had in mind?

Wouldn't it be possible to chain `MinMaxScaler` and `FeatureUnion` together in the "mapper" step? Something like `[MinMaxScaler(), FeatureUnion(...)]`.

At the moment, the `FeatureUnion` transformation is applied to all columns that come out of the "mapper" step. That would be problematic if you had more columns than just "A" and "B" in your dataset.

**Comment by rwjmiller** [comment]
That would certainly be simpler, but if I try to move the FeatureUnion from the example above into the mapper step, I get a Python error. I think as long as I make sure that the initial mapper step in the sub-pipeline only picks up those two columns, it should work as required.

Code:
```
mapper = DataFrameMapper([
    (['A','B'],[
        MinMaxScaler(feature_range=(0,2*3.14159)),
        FeatureUnion([
            ("sin",FunctionTransformer(np.sin)),
            ("cos",FunctionTransformer(np.cos))
        ])        
    ])
])

pipeline = PMMLPipeline([
    ("mapper", mapper),
    ("regressor", XGBRegressor())
])

pipeline.fit(df, df.C)
sklearn2pmml(pipeline,"pipeline_05.pmml")
```
Error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-33-a6e2cc3a7de9> in <module>()
     14 ])
     15 
---> 16 pipeline.fit(df, df.C)
     17 sklearn2pmml(pipeline,"pipeline_05.pmml")

/opt/conda/lib/python3.6/site-packages/sklearn/pipeline.py in fit(self, X, y, **fit_params)
    246             This estimator
    247         """
--> 248         Xt, fit_params = self._fit(X, y, **fit_params)
    249         if self._final_estimator is not None:
    250             self._final_estimator.fit(Xt, y, **fit_params)

/opt/conda/lib/python3.6/site-packages/sklearn2pmml/__init__.py in _fit(self, X, y, **fit_params)
     68                 if target_fields is not None:
     69                         self.target_fields = target_fields
---> 70                 return super(PMMLPipeline, self)._fit(X = X, y = y, **fit_params)
     71 
     72         def verify(self, X, precision = 1e-13, zeroThreshold = 1e-13):

/opt/conda/lib/python3.6/site-packages/sklearn/pipeline.py in _fit(self, X, y, **fit_params)
    211                 Xt, fitted_transformer = fit_transform_one_cached(
    212                     cloned_transformer, None, Xt, y,
--> 213                     **fit_params_steps[name])
    214                 # Replace the transformer of the step with the fitted
    215                 # transformer. This is necessary when loading the transformer

/opt/conda/lib/python3.6/site-packages/sklearn/externals/joblib/memory.py in __call__(self, *args, **kwargs)
    360 
    361     def __call__(self, *args, **kwargs):
--> 362         return self.func(*args, **kwargs)
    363 
    364     def call_and_shelve(self, *args, **kwargs):

/opt/conda/lib/python3.6/site-packages/sklearn/pipeline.py in _fit_transform_one(transformer, weight, X, y, **fit_params)
    579                        **fit_params):
    580     if hasattr(transformer, 'fit_transform'):
--> 581         res = transformer.fit_transform(X, y, **fit_params)
    582     else:
    583         res = transformer.fit(X, y, **fit_params).transform(X)

/opt/conda/lib/python3.6/site-packages/sklearn/base.py in fit_transform(self, X, y, **fit_params)
    518         else:
    519             # fit method of arity 2 (supervised transformation)
--> 520             return self.fit(X, y, **fit_params).transform(X)
    521 
    522 

/opt/conda/lib/python3.6/site-packages/sklearn_pandas/dataframe_mapper.py in transform(self, X)
    282             alias = options.get('alias')
    283             self.transformed_names_ += self.get_names(
--> 284                 columns, transformers, Xt, alias)
    285 
    286         # handle features not explicitly selected

/opt/conda/lib/python3.6/site-packages/sklearn_pandas/dataframe_mapper.py in get_names(self, columns, transformer, x, alias)
    249                 estimators = (estimator for name, estimator in inverse_steps)
    250                 names_steps = (_get_feature_names(e) for e in estimators)
--> 251                 names = next((n for n in names_steps if n is not None), None)
    252             # Otherwise use the only estimator present
    253             else:

/opt/conda/lib/python3.6/site-packages/sklearn_pandas/dataframe_mapper.py in <genexpr>(.0)
    249                 estimators = (estimator for name, estimator in inverse_steps)
    250                 names_steps = (_get_feature_names(e) for e in estimators)
--> 251                 names = next((n for n in names_steps if n is not None), None)
    252             # Otherwise use the only estimator present
    253             else:

/opt/conda/lib/python3.6/site-packages/sklearn_pandas/dataframe_mapper.py in <genexpr>(.0)
    248                 inverse_steps = transformer.steps[::-1]
    249                 estimators = (estimator for name, estimator in inverse_steps)
--> 250                 names_steps = (_get_feature_names(e) for e in estimators)
    251                 names = next((n for n in names_steps if n is not None), None)
    252             # Otherwise use the only estimator present

/opt/conda/lib/python3.6/site-packages/sklearn_pandas/dataframe_mapper.py in _get_feature_names(estimator)
     45         return estimator.classes_
     46     elif hasattr(estimator, 'get_feature_names'):
---> 47         return estimator.get_feature_names()
     48     return None
     49 

/opt/conda/lib/python3.6/site-packages/sklearn/pipeline.py in get_feature_names(self)
    687                 raise AttributeError("Transformer %s (type %s) does not "
    688                                      "provide get_feature_names."
--> 689                                      % (str(name), type(trans).__name__))
    690             feature_names.extend([name + "__" + f for f in
    691                                   trans.get_feature_names()])

AttributeError: Transformer sin (type FunctionTransformer) does not provide get_feature_names.
```
