### ISSUE TITLE
Numpy array of `int8` values causes PMML export to error out

### ISSUE THREAD

**Issue by hanbinggan** [jpmml/sklearn2pmml#90]
I use  scipy sparse as X train the model
I am getting an error when I try to convert model to pmml.
Here is the stack trace:

```
Standard output is empty
Traceback (most recent call last):
  File "show_demo.py", line 32, in <module>
Standard error:
Mar 23, 2018 11:34:32 AM org.jpmml.sklearn.Main run
??: Parsing PKL..
    sklearn2pmml(pipeline, 'linear_svc.pmml')
Mar 23, 2018 11:34:32 AM org.jpmml.sklearn.Main run
  File "venv/lib/python2.7/site-packages/sklearn2pmml/__init__.py", line 237, in sklearn2pmml
??: Failed to parse PKL
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
java.io.IOException
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
	at numpy.core.NDArrayUtil$TypeDescriptor.read(NDArrayUtil.java:534)
	at numpy.core.NDArrayUtil.parseArray(NDArrayUtil.java:215)
	at numpy.core.NDArrayUtil.parseData(NDArrayUtil.java:190)
	at joblib.NumpyArrayWrapper.toArray(NumpyArrayWrapper.java:43)
	at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:88)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
	at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)
	at org.jpmml.sklearn.Main.run(Main.java:104)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.io.IOException
	at numpy.core.NDArrayUtil$TypeDescriptor.read(NDArrayUtil.java:534)
	at numpy.core.NDArrayUtil.parseArray(NDArrayUtil.java:215)
	at numpy.core.NDArrayUtil.parseData(NDArrayUtil.java:190)
	at joblib.NumpyArrayWrapper.toArray(NumpyArrayWrapper.java:43)
	at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:88)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
	at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)
	at org.jpmml.sklearn.Main.run(Main.java:104)
	at org.jpmml.sklearn.Main.main(Main.java:94)
```

Below is the code that reproduces this error.
```
# coding: utf-8
import numpy as np
import scipy.sparse as sparse
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn2pmml import sklearn2pmml
from sklearn2pmml.pipeline import PMMLPipeline

x_data_file_name = 'tmp_x.npz'

y_data_file_name = 'tmp_y.npy'

X = sparse.load_npz(x_data_file_name)
X = X.tocsr()

Y = np.load(open(y_data_file_name))
random_state = 13
test_size = 0.1

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=random_state)

clf = LinearSVC(random_state=13, C=0.402, max_iter=1000)

pipeline = PMMLPipeline(
    [
        ('classifier', clf), ])

pipeline.fit(x_train, y_train)
# pipeline.active_fields = np.array([str(x) for x in range(1, x_train.shape[1] + 1)])
# pipeline.target_fields = 'y'

sklearn2pmml(pipeline, 'linear_svc.pmml')
print('linear svc  linear_svc.pmml model saved')

```

1. 
I try specity their column names as PMMLPipeline.active_fields and PMMLPipeline.target_field attributes:
```
pipeline.active_fields = np.array([str(x) for x in range(1, x_train.shape[1] + 1)])
pipeline.target_fields = 'y'
```
the error is same as before.
2. 
I try convert X and y arguments from Numpy arrays to pandas.DataFrame and pandas.Series objects:
```
print('x after size: %s' % sys.getsizeof(x_train))
x_train = pd.SparseDataFrame(x_train, default_fill_value=0).to_sparse(fill_value=0)
print('x after size: %s' % sys.getsizeof(x_train))

y_train = pd.Series(y_train)
```
I also meet the same error. AND the SparseDataFrame type cost too much memory to OOM.
3.
I use SVC instead of  Linear SVC .error appear as before.

Here are my environment:
```
python: 2.7.14
sklearn: 0.19.1
pandas: 0.22.0
sklearn2pmml: 0.33.0
sklearn_pandas: 1.6.0
scipy: 1.0.0
```

Any thoughts on what might be going on here?

**Comment by vruusmann** [comment]
The JPMML-SkLearn library supports Scipy sparse matrices (`scipy.sparse.csr.csr_matrix`).

> Exception in thread "main" java.io.IOException
>	at numpy.core.NDArrayUtil$TypeDescriptor.read(NDArrayUtil.java:534)
>	at numpy.core.NDArrayUtil.parseArray(NDArrayUtil.java:215)

If you take a look inside the `NDArrayUtil#read(InputStream)` method, then it's easy to see that this `IOException` is thrown at the very end, if the element kind didn't match. In other words, your sparse matrix contains values that are not recognized.

What's the data type of `tmp_x.npz` and/or `tmp_y.npy` files? Some 8-bit, or unsigned number types?

**Comment by hanbinggan** [comment]
tmp_x.npz type is float32.
tmp_y.npy type is int8.
I send the file to you email.

**Comment by vruusmann** [comment]
> tmp_y.npy type is int8.

The `int8` data type is not supported. If you cast the data type of `Y` from `int8` to `int32` (or `int64`), then everything should work fine.

**Comment by hanbinggan** [comment]
I try change y dtype
`Y = np.array(Y, dtype=np.int32)`
before error has solved. but I meet a new error.
Here is the stack trace:

```
venv/bin/python show_demo.py
Standard output is empty
Standard error:
Mar 23, 2018 3:38:49 PM org.jpmml.sklearn.Main run
??: Parsing PKL..
Mar 23, 2018 3:39:18 PM org.jpmml.sklearn.Main run
??: Parsed PKL in 28793 ms.
Mar 23, 2018 3:39:18 PM org.jpmml.sklearn.Main run
??: Converting..
Mar 23, 2018 3:39:18 PM org.jpmml.sklearn.Main run
??: Failed to convert
java.lang.IllegalArgumentException: Tuple contains an unsupported value (Python class sklearn.svm.classes.LinearSVC)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at org.jpmml.sklearn.TupleUtil.extractElement(TupleUtil.java:48)
	at sklearn2pmml.pipeline.PMMLPipeline.getEstimator(PMMLPipeline.java:369)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:85)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Estimator
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 5 more

Exception in thread "main" java.lang.IllegalArgumentException: Tuple contains an unsupported value (Python class sklearn.svm.classes.LinearSVC)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at org.jpmml.sklearn.TupleUtil.extractElement(TupleUtil.java:48)
	at sklearn2pmml.pipeline.PMMLPipeline.getEstimator(PMMLPipeline.java:369)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:85)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Estimator
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 5 more

Traceback (most recent call last):
  File "show_demo.py", line 43, in <module>
    sklearn2pmml(pipeline, 'linear_svc.pmml')
  File "venv/lib/python2.7/site-packages/sklearn2pmml/__init__.py", line 237, in sklearn2pmml
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams

Process finished with exit code 1

```

my os env
`Darwin MacBook-Pro-3.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64`

**Comment by vruusmann** [comment]
> java.lang.IllegalArgumentException: Tuple contains an unsupported value (Python class sklearn.svm.classes.LinearSVC)

The `LinearSVC` model type is not supported yet.

See https://github.com/jpmml/jpmml-sklearn/issues/56

**Comment by hanbinggan** [comment]
I try use SVC.
`clf = SVC(C=0.402, kernel='linear')`
before error has solved. but I meet a new error.
my sparse matrix too large to OOM.
Here is the stack trace:

```
venv/bin/python show_demo.py
Standard output is empty
Standard error:
Mar 23, 2018 3:51:53 PM org.jpmml.sklearn.Main run
??: Parsing PKL..
Mar 23, 2018 3:51:56 PM org.jpmml.sklearn.Main run
??: Parsed PKL in 3341 ms.
Mar 23, 2018 3:51:56 PM org.jpmml.sklearn.Main run
??: Converting..
Mar 23, 2018 3:51:56 PM sklearn2pmml.pipeline.PMMLPipeline encodePMML
??: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
Mar 23, 2018 3:51:56 PM sklearn2pmml.pipeline.PMMLPipeline initFeatures
??: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.active_fields' is not set. Assuming [x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20,x127804, x127805, x127806, x127807, x127808, x127809, x127810, x127811, x127812, x127813, x127814, x127815, x127816, x127817, x127818, x127819, x127820, x127821, x127822, x127823, x127824, x127825, x127826, x127827, x127828, x127829, x127830, x127831, x127832, x127833, x127834, x127835, x127836, x127837, x127838, x127839, x127840, x127841, x127842, x127843, x127844, x127845, x127846, x127847, x127848] as the names of active fields
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.ArrayList.<init>(ArrayList.java:152)
	at scipy.sparse.CSRMatrixUtil.getContent(CSRMatrixUtil.java:57)
	at scipy.sparse.CSRMatrix.getArrayContent(CSRMatrix.java:35)
	at org.jpmml.sklearn.PyClassDict.getArray(PyClassDict.java:71)
	at org.jpmml.sklearn.PyClassDict.getArray(PyClassDict.java:82)
	at sklearn.svm.LibSVMClassifier.getSupportVectors(LibSVMClassifier.java:99)
	at sklearn.svm.LibSVMClassifier.encodeModel(LibSVMClassifier.java:57)
	at sklearn.svm.LibSVMClassifier.encodeModel(LibSVMClassifier.java:31)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:161)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Traceback (most recent call last):
  File "show_demo.py", line 44, in <module>
    sklearn2pmml(pipeline, 'linear_svc.pmml')
  File "venv/lib/python2.7/site-packages/sklearn2pmml/__init__.py", line 237, in sklearn2pmml
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams

Process finished with exit code 1
```

**Comment by 18256065810** [comment]
I print the error out:
b'\xbe\xc5\xd4\xc2 05, 2018 6:25:11 \xcf\xc2\xce\xe7 org.jpmml.sklearn.Main run\r\n\xd0\xc5\xcf\xa2: Parsing PKL..\r\n\xbe\xc5\xd4\xc2 05, 2018 6:25:26 \xcf\xc2\xce\xe7 org.jpmml.sklearn.Main run\r\n\xd0\xc5\xcf\xa2: Parsed PKL in 15008 ms.\r\n\xbe\xc5\xd4\xc2 05, 2018 6:25:26 \xcf\xc2\xce\xe7 org.jpmml.sklearn.Main run\r\n\xd0\xc5\xcf\xa2: Converting..\r\nException in thread "main" java.lang.OutOfMemoryError: Java heap space\r\n\tat java.util.ArrayList.<init>(Unknown Source)\r\n\tat scipy.sparse.CSRMatrixUtil.getContent(CSRMatrixUtil.java:57)\r\n\tat scipy.sparse.CSRMatrix.getArrayContent(CSRMatrix.java:35)\r\n\tat org.jpmml.sklearn.PyClassDict.getArray(PyClassDict.java:71)\r\n\tat org.jpmml.sklearn.PyClassDict.getArray(PyClassDict.java:82)\r\n\tat sklearn.svm.LibSVMClassifier.getSupportVectors(LibSVMClassifier.java:99)\r\n\tat sklearn.svm.LibSVMClassifier.encodeModel(LibSVMClassifier.java:57)\r\n\tat sklearn.svm.LibSVMClassifier.encodeModel(LibSVMClassifier.java:31)\r\n\tat sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:209)\r\n\tat org.jpmml.sklearn.Main.run(Main.java:145)\r\n\tat org.jpmml.sklearn.Main.main(Main.java:94)\r\n'

so I know that is "java.lang.OutOfMemoryError". Then I change my code as :+1: 
from sklearn2pmml import sklearn2pmml
import os
os.environ["_JAVA_OPTIONS"] = "-Xms2G -Xmx4G"

sklearn2pmml(pipeline, "linear_svc.pmml")

and it still runs after 1 hour, So slow !  So how can I to solve it ？
