### ISSUE TITLE
Adding lemmatizer to CountVectorizer

### ISSUE THREAD

**Issue by someshjainiitkgp** [jpmml/sklearn2pmml#91]
```
Exception - SEVERE: Failed to parse PKL
net.razorvine.pickle.PickleException: failed to __setstate__()
	at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:368)
	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:221)
	at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:77)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
	at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)
	at org.jpmml.sklearn.Main.run(Main.java:104)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.NoSuchMethodException: net.razorvine.pickle.objects.ClassDict.__setstate__(net.razorvine.pickle.objects.ClassDict)
	at java.lang.Class.getMethod(Class.java:1786)
	at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:365)
	... 6 more

Exception in thread "main" net.razorvine.pickle.PickleException: failed to __setstate__()
	at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:368)
	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:221)
	at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:77)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
	at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)
	at org.jpmml.sklearn.Main.run(Main.java:104)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.NoSuchMethodException: net.razorvine.pickle.objects.ClassDict.__setstate__(net.razorvine.pickle.objects.ClassDict)
	at java.lang.Class.getMethod(Class.java:1786)
	at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:365)
	... 6 more
```

```
class LemmaTokenizer:
    def __init__(self):
        self.wnl = WordNetLemmatizer()
    def __call__(self, text):
        tokens = [self.wnl.lemmatize(t) for t in word_tokenize(text)]
        return tuple(tokens)

subjectVectorizer = CountVectorizer(stop_words='english',
                                    binary=True,
                                    ngram_range=(1, 3),
                                    max_df=1.0,
                                    min_df=2,
                                    tokenizer=LemmaTokenizer()
                                    )

clf = LogisticRegressionCV(Cs=list(np.power(10.0, np.arange(-10, 10))),
                           solver="liblinear", penalty="l1", cv=5, scoring='roc_auc',
                           class_weight="balanced", random_state=20171227, max_iter=500)

dataFrameList.append(("subject", subjectVectorizer))
pipeline = PMMLPipeline([
    ("mapper", DataFrameMapper(dataFrameList, sparse=True)),
    ("classifier", clf)
])
pipeline.fit(featuresDF, labelDF)

sklearn2pmml(pipeline, 'model.pmml')

```

**Comment by vruusmann** [comment]
> subjectVectorizer = CountVectorizer(tokenizer=LemmaTokenizer())

The `tokenizer` attribute must be of type `sklearn2pmml.feature_extraction.text.Splitter`.

**Comment by vruusmann** [comment]
Closing as unfixable.

As explained previously in #150, it's impossible to translate the business logic of 3rd party libraries (here, class `WordNetLemmatizer`) to PMML.
